module.exports = [
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "40",
    duration: "5h",
    from: "Paris",
    to: "Lyon",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Marseille",
    to: "Toulouse",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "60",
    duration: "8h",
    from: "Bordeaux",
    to: "Nice",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "6h",
    from: "Lille",
    to: "Nantes",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "70",
    duration: "9h",
    from: "Strasbourg",
    to: "Montpellier",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Grenoble",
    to: "Nimes",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "3h",
    from: "Rennes",
    to: "Caen",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "50",
    duration: "6h",
    from: "Avignon",
    to: "Dijon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "55",
    duration: "7h",
    from: "Brest",
    to: "Tours",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Rouen",
    to: "Angers",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "11h",
    from: "Nancy",
    to: "Perpignan",
  },
  {
    amenities: "Wheelchair lift, accessible seating",
    cost: "55",
    duration: "6h 30m",
    from: "Limoges",
    to: "Besancon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "70",
    duration: "9h",
    from: "Toulon",
    to: "Strasbourg",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "20",
    duration: "2h",
    from: "Saint-Etienne",
    to: "Clermont-Ferrand",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "12h",
    from: "Nice",
    to: "Lille",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "9h 30m",
    from: "Metz",
    to: "Montauban",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h",
    from: "Annecy",
    to: "Orleans",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Valence",
    to: "Lehavre",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "95",
    duration: "13h",
    from: "Aix-en-Provence",
    to: "Brest",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Tours",
    to: "Amiens",
  },
  {
    amenities: "Wheelchair lift, accessible seating",
    cost: "35",
    duration: "4h 30m",
    from: "Nantes",
    to: "Rouen",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "12h",
    from: "Lemans",
    to: "Nice",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "10h",
    from: "Bordeaux",
    to: "Lille",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Lyon",
    to: "Rennes",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "70",
    duration: "9h",
    from: "Montpellier",
    to: "Caen",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Lorient",
    to: "Valenciennes",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "11h",
    from: "Agen",
    to: "Mulhouse",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Chalon-sur-Saone",
    to: "La Rochelle",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Bayonne",
    to: "Reims",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h 30m",
    from: "Poitiers",
    to: "Nancy",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "9h 30m",
    from: "Lehavre",
    to: "Toulouse",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h 30m",
    from: "Bergerac",
    to: "Lyon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Chartres",
    to: "Marseille",
  },
  {
    amenities: "Wheelchair lift, accessible seating, on-board restroom",
    cost: "75",
    duration: "9h 30m",
    from: "Niort",
    to: "Grenoble",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "8h",
    from: "Saint-Nazaire",
    to: "Limoges",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "10h 30m",
    from: "Auxerre",
    to: "Montpellier",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Ales",
    to: "Rennes",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "12h",
    from: "Dunkirk",
    to: "Avignon",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "75",
    duration: "9h 30m",
    from: "Chateauroux",
    to: "Strasbourg",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Colmar",
    to: "Nantes",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Aurillac",
    to: "Lille",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "10h",
    from: "Annemasse",
    to: "Bordeaux",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "95",
    duration: "13h",
    from: "Arras",
    to: "Nice",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Carcassonne",
    to: "Rouen",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "5h 30m",
    from: "Brive-la-Gaillarde",
    to: "Tours",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "90",
    duration: "12h",
    from: "Vancouver",
    to: "Edmonton",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "50",
    duration: "6h 30m",
    from: "Toronto",
    to: "Montreal",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "120",
    duration: "16h",
    from: "Ottawa",
    to: "Halifax",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h",
    from: "Winnipeg",
    to: "Saskatoon",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "70",
    duration: "8h 30m",
    from: "Calgary",
    to: "Regina",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "125",
    duration: "16h 30m",
    from: "Halifax",
    to: "St. John's",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h",
    from: "Montreal",
    to: "Quebec City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "175",
    duration: "22h 30m",
    from: "Edmonton",
    to: "Yellowknife",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "110",
    duration: "15h",
    from: "Vancouver",
    to: "Calgary",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "40",
    duration: "5h",
    from: "Toronto",
    to: "Ottawa",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "130",
    duration: "16h 30m",
    from: "Saskatoon",
    to: "Yellowknife",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "160",
    duration: "22h",
    from: "Halifax",
    to: "Toronto",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "250",
    duration: "32h",
    from: "Vancouver",
    to: "Whitehorse",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "11h 30m",
    from: "Quebec City",
    to: "Moncton",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Regina",
    to: "Winnipeg",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "375",
    duration: "48h",
    from: "Toronto",
    to: "Vancouver",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "125",
    duration: "16h 30m",
    from: "St. John's",
    to: "Halifax",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "100",
    duration: "13h",
    from: "Edmonton",
    to: "Vancouver",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "50",
    duration: "6h",
    from: "Montreal",
    to: "Toronto",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "130",
    duration: "17h",
    from: "Yellowknife",
    to: "Whitehorse",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h",
    from: "Vancouver",
    to: "Prince George",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Ottawa",
    to: "Toronto",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Edmonton",
    to: "Saskatoon",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "5h 30m",
    from: "Halifax",
    to: "Charlottetown",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "105",
    duration: "14h",
    from: "Calgary",
    to: "Vancouver",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "100",
    duration: "11h",
    from: "Toronto",
    to: "New York City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "90",
    duration: "11h 30m",
    from: "Winnipeg",
    to: "Thunder Bay",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "5h 30m",
    from: "Halifax",
    to: "Sydney",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Vancouver",
    to: "Kamloops",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h 30m",
    from: "Edmonton",
    to: "Calgary",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "110",
    duration: "14h",
    from: "Montreal",
    to: "Halifax",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h",
    from: "Regina",
    to: "Calgary",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "95",
    duration: "12h 30m",
    from: "Yellowknife",
    to: "FortmcMurray",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "40",
    duration: "5h",
    from: "Toronto",
    to: "Ottawa",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "4h",
    from: "St. John's",
    to: "Gander",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "4h",
    from: "Vancouver",
    to: "Victoria",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h 30m",
    from: "Ottawa",
    to: "Montreal",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h 30m",
    from: "Saskatoon",
    to: "Regina",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "120",
    duration: "13h",
    from: "Halifax",
    to: "Boston",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h 30m",
    from: "Edmonton",
    to: "Jasper",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "4h 30m",
    from: "Windsor City",
    to: "Toronto",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "20",
    duration: "2h",
    from: "Windsor City",
    to: "London",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "7h 30m",
    from: "Windsor City",
    to: "Ottawa",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "10",
    duration: "30m",
    from: "Windsor City",
    to: "Detroit",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h",
    from: "Windsor City",
    to: "Niagara Falls",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "15",
    duration: "1h 30m",
    from: "Windsor City",
    to: "Sarnia",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h",
    from: "Windsor City",
    to: "Hamilton",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "7h 30m",
    from: "Windsor City",
    to: "Montreal",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "3h 30m",
    from: "Windsor City",
    to: "Kitchener",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "70",
    duration: "7h",
    from: "Windsor City",
    to: "Sudbury",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "170",
    duration: "17h",
    from: "Windsor City",
    to: "Thunder Bay",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "6h",
    from: "Windsor City",
    to: "Kingston",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "85",
    duration: "8h 30m",
    from: "Windsor City",
    to: "North Bay",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "120",
    duration: "12h",
    from: "Windsor City",
    to: "Quebec City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "360",
    duration: "36h",
    from: "Windsor City",
    to: "Calgary",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "390",
    duration: "39h",
    from: "Windsor City",
    to: "Edmonton",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "480",
    duration: "48h",
    from: "Windsor City",
    to: "Vancouver",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "270",
    duration: "27h",
    from: "Windsor City",
    to: "Halifax",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "220",
    duration: "22h",
    from: "Windsor City",
    to: "Winnipeg",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "600",
    duration: "60h",
    from: "Windsor City",
    to: "Yellowknife",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h",
    from: "Abu Dhabi",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "10",
    duration: "1hour",
    from: "Dubai",
    to: "Sharjah",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Al Ain",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h",
    from: "Dubai",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "3h",
    from: "Dubai",
    to: "Fujairah",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "8h",
    from: "Abu Dhabi",
    to: "Muscat (Oman)",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "15",
    duration: "1h 30m",
    from: "Dubai",
    to: "Ras Al Khaimah",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai Airport",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai",
    to: "Abu Dhabi Airport",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "3h",
    from: "Abu Dhabi",
    to: "Al Gharbia",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai",
    to: "Abu Dhabi - Al Reem Island",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "10",
    duration: "1hour",
    from: "Dubai",
    to: "Ajman",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Ibn Battuta",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "15",
    duration: "1h 30m",
    from: "Dubai",
    to: "Umm Al Quwain",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Jumeirah",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Al Qusais",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai -mall of the Emirates",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Al Satwa",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Almaktoum Airport",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Jebel Ali",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai",
    to: "Abu Dhabi - Saadiyat Island",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubai Festival City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Al Rashidiya",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Al Quoz",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Al Barsha",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Business Bay",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Deira City Center",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubai Internet City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Downtown",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubai Design District",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Jumeirah Beach Residence",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubaimedia City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - The Greens",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubai Sports City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - World Trade Center",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubai Silicon Oasis",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Dubaimarina",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - Dubai Investment Park",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai",
    to: "Dubai - Dubaihealthcare City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi",
    to: "Dubai - The Palm Jumeirah",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "40",
    duration: "5h",
    from: "Lyon",
    to: "Paris",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Toulouse",
    to: "Marseille",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "60",
    duration: "8h",
    from: "Nice",
    to: "Bordeaux",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "6h",
    from: "Nantes",
    to: "Lille",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "70",
    duration: "9h",
    from: "Montpellier",
    to: "Strasbourg",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Nimes",
    to: "Grenoble",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "3h",
    from: "Caen",
    to: "Rennes",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "50",
    duration: "6h",
    from: "Dijon",
    to: "Avignon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "55",
    duration: "7h",
    from: "Tours",
    to: "Brest",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Angers",
    to: "Rouen",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "11h",
    from: "Perpignan",
    to: "Nancy",
  },
  {
    amenities: "Wheelchair lift, accessible seating",
    cost: "55",
    duration: "6h 30m",
    from: "Besancon",
    to: "Limoges",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "70",
    duration: "9h",
    from: "Strasbourg",
    to: "Toulon",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "20",
    duration: "2h",
    from: "Clermont-Ferrand",
    to: "Saint-Etienne",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "12h",
    from: "Lille",
    to: "Nice",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "9h 30m",
    from: "Montauban",
    to: "Metz",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h",
    from: "Orleans",
    to: "Annecy",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Lehavre",
    to: "Valence",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "95",
    duration: "13h",
    from: "Brest",
    to: "Aix-en-Provence",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Amiens",
    to: "Tours",
  },
  {
    amenities: "Wheelchair lift, accessible seating",
    cost: "35",
    duration: "4h 30m",
    from: "Rouen",
    to: "Nantes",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "12h",
    from: "Nice",
    to: "Lemans",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "10h",
    from: "Lille",
    to: "Bordeaux",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Rennes",
    to: "Lyon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "70",
    duration: "9h",
    from: "Caen",
    to: "Montpellier",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Valenciennes",
    to: "Lorient",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "11h",
    from: "Mulhouse",
    to: "Agen",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "La Rochelle",
    to: "Chalon-sur-Saone",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Reims",
    to: "Bayonne",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h 30m",
    from: "Nancy",
    to: "Poitiers",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "9h 30m",
    from: "Toulouse",
    to: "Lehavre",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h 30m",
    from: "Lyon",
    to: "Bergerac",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Marseille",
    to: "Chartres",
  },
  {
    amenities: "Wheelchair lift, accessible seating, on-board restroom",
    cost: "75",
    duration: "9h 30m",
    from: "Grenoble",
    to: "Niort",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "8h",
    from: "Limoges",
    to: "Saint-Nazaire",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "10h 30m",
    from: "Montpellier",
    to: "Auxerre",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Rennes",
    to: "Ales",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "12h",
    from: "Avignon",
    to: "Dunkirk",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "75",
    duration: "9h 30m",
    from: "Strasbourg",
    to: "Chateauroux",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Nantes",
    to: "Colmar",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Lille",
    to: "Aurillac",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "80",
    duration: "10h",
    from: "Bordeaux",
    to: "Annemasse",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "95",
    duration: "13h",
    from: "Nice",
    to: "Arras",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "85",
    duration: "11h 30m",
    from: "Rouen",
    to: "Carcassonne",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "5h 30m",
    from: "Tours",
    to: "Brive-la-Gaillarde",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "90",
    duration: "12h",
    from: "Edmonton",
    to: "Vancouver",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "50",
    duration: "6h 30m",
    from: "Montreal",
    to: "Toronto",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "120",
    duration: "16h",
    from: "Halifax",
    to: "Ottawa",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h",
    from: "Saskatoon",
    to: "Winnipeg",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "70",
    duration: "8h 30m",
    from: "Regina",
    to: "Calgary",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "125",
    duration: "16h 30m",
    from: "St. John's",
    to: "Halifax",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h",
    from: "Quebec City",
    to: "Montreal",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "175",
    duration: "22h 30m",
    from: "Yellowknife",
    to: "Edmonton",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "110",
    duration: "15h",
    from: "Calgary",
    to: "Vancouver",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "40",
    duration: "5h",
    from: "Ottawa",
    to: "Toronto",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "130",
    duration: "16h 30m",
    from: "Yellowknife",
    to: "Saskatoon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "160",
    duration: "22h",
    from: "Toronto",
    to: "Halifax",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "250",
    duration: "32h",
    from: "Whitehorse",
    to: "Vancouver",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "11h 30m",
    from: "Moncton",
    to: "Quebec City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Winnipeg",
    to: "Regina",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "375",
    duration: "48h",
    from: "Vancouver",
    to: "Toronto",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "125",
    duration: "16h 30m",
    from: "Halifax",
    to: "St. John's",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "100",
    duration: "13h",
    from: "Vancouver",
    to: "Edmonton",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "50",
    duration: "6h",
    from: "Toronto",
    to: "Montreal",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "130",
    duration: "17h",
    from: "Whitehorse",
    to: "Yellowknife",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h",
    from: "Prince George",
    to: "Vancouver",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Toronto",
    to: "Ottawa",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "7h 30m",
    from: "Saskatoon",
    to: "Edmonton",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "5h 30m",
    from: "Charlottetown",
    to: "Halifax",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "105",
    duration: "14h",
    from: "Vancouver",
    to: "Calgary",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "100",
    duration: "11h",
    from: "New York City",
    to: "Toronto",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "90",
    duration: "11h 30m",
    from: "Thunder Bay",
    to: "Winnipeg",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "5h 30m",
    from: "Sydney",
    to: "Halifax",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "4h 30m",
    from: "Kamloops",
    to: "Vancouver",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h 30m",
    from: "Calgary",
    to: "Edmonton",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "110",
    duration: "14h",
    from: "Halifax",
    to: "Montreal",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "65",
    duration: "8h",
    from: "Calgary",
    to: "Regina",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "95",
    duration: "12h 30m",
    from: "FortmcMurray",
    to: "Yellowknife",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "40",
    duration: "5h",
    from: "Ottawa",
    to: "Toronto",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "4h",
    from: "Gander",
    to: "St. John's",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "4h",
    from: "Victoria",
    to: "Vancouver",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h 30m",
    from: "Montreal",
    to: "Ottawa",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h 30m",
    from: "Regina",
    to: "Saskatoon",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "120",
    duration: "13h",
    from: "Boston",
    to: "Halifax",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h 30m",
    from: "Jasper",
    to: "Edmonton",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "45",
    duration: "4h 30m",
    from: "Toronto",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "20",
    duration: "2h",
    from: "London",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "7h 30m",
    from: "Ottawa",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "10",
    duration: "30m",
    from: "Detroit",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h",
    from: "Niagara Falls",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "15",
    duration: "1h 30m",
    from: "Sarnia",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "3h",
    from: "Hamilton",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "75",
    duration: "7h 30m",
    from: "Montreal",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "3h 30m",
    from: "Kitchener",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "70",
    duration: "7h",
    from: "Sudbury",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "170",
    duration: "17h",
    from: "Thunder Bay",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "60",
    duration: "6h",
    from: "Kingston",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "85",
    duration: "8h 30m",
    from: "North Bay",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "120",
    duration: "12h",
    from: "Quebec City",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "360",
    duration: "36h",
    from: "Calgary",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "390",
    duration: "39h",
    from: "Edmonton",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "480",
    duration: "48h",
    from: "Vancouver",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "270",
    duration: "27h",
    from: "Halifax",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "220",
    duration: "22h",
    from: "Winnipeg",
    to: "Windsor City",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "600",
    duration: "60h",
    from: "Yellowknife",
    to: "Windsor City",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h",
    from: "Dubai",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "10",
    duration: "1hour",
    from: "Sharjah",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Al Ain",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "25",
    duration: "2h",
    from: "Abu Dhabi",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "3h",
    from: "Fujairah",
    to: "Dubai",
  },
  {
    amenities:
      "Wheelchair lift, accessible seating, audio announcements, on-board restroom",
    cost: "90",
    duration: "8h",
    from: "Muscat (Oman)",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "15",
    duration: "1h 30m",
    from: "Ras Al Khaimah",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai Airport",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi Airport",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "35",
    duration: "3h",
    from: "Al Gharbia",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi - Al Reem Island",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "10",
    duration: "1hour",
    from: "Ajman",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Ibn Battuta",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "15",
    duration: "1h 30m",
    from: "Umm Al Quwain",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Jumeirah",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Al Qusais",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai -mall of the Emirates",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Al Satwa",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Almaktoum Airport",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Jebel Ali",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Abu Dhabi - Saadiyat Island",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubai Festival City",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Al Rashidiya",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Al Quoz",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Al Barsha",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Business Bay",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Deira City Center",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubai Internet City",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Downtown",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubai Design District",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Jumeirah Beach Residence",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubaimedia City",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - The Greens",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubai Sports City",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - World Trade Center",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubai Silicon Oasis",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Dubaimarina",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - Dubai Investment Park",
    to: "Abu Dhabi",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "5",
    duration: "30m",
    from: "Dubai - Dubaihealthcare City",
    to: "Dubai",
  },
  {
    amenities: "Wheelchair lift, accessible seating, audio announcements",
    cost: "30",
    duration: "2h 30m",
    from: "Dubai - The Palm Jumeirah",
    to: "Abu Dhabi",
  },
];
