module.exports = [
  {
    Type: "Hotel",
    Accomodations: "Best Western Hotel Charlemagne",
    price: "117",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "La Villa des Fleurs",
    price: "86",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Napoleon",
    price: "178",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Aubiers",
    price: "74",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nantes",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel La Rochelle",
    price: "79",
    Ammenities: "Accessible Bathroom, Accessible Entrance",
    Location: "La Rochelle",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Trianon Rive Gauche",
    price: "229",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Mercure Lyon Centre Plaza",
    price: "184",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Majestic",
    price: "339",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Cannes",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Ang\u00c3\u00a8le",
    price: "70",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nantes",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Pont",
    price: "93",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Bayonne",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Oliviers",
    price: "56",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Meridien Etoile",
    price: "307",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Sofitel Lyon Bellecour",
    price: "304",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Carcassonne",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite",
    price: "143",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Carcassonne",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Costes",
    price: "301",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Europe",
    price: "70",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Strasbourg",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison des Ch\u00c3\u00aanes",
    price: "100",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Bordeaux",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Annecy",
    price: "65",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Saint-Georges",
    price: "60",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Montpellier",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les G\u00c3\u00aetes du Littoral",
    price: "90",
    Ammenities: "Accessible Rooms, Accessible Bathroom",
    Location: "Saint-Malo",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de Jean",
    price: "96",
    Ammenities: "Accessible Shower, Accessible Rooms",
    Location: "Marseille",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Plaza Athenee",
    price: "370",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Antibes",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Tilleuls",
    price: "67",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Rennes",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Saint Germain",
    price: "127",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel du Cap-Eden-Roc",
    price: "400",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Antibes",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Biarritz",
    price: "85",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Biarritz",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison des Ch\u00c3\u00aanes",
    price: "91",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Bordeaux",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Avignon",
    price: "85",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Avignon",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel InterContinental",
    price: "271",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Marseille",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "304",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "309",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Studios du Louvre",
    price: "80",
    Ammenities: "Accessible Bathroom, Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Poitiers",
    price: "58",
    Ammenities: "Braille Signage, Visual Alarm/Alert in Guest Rooms",
    Location: "Poitiers",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Paris",
    price: "105",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lourdes",
    price: "114",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Bathroom",
    Location: "Lourdes",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Havre",
    price: "82",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Le Havre",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nice",
    price: "85",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Suites de la Potini\u00c3\u00a8re",
    price: "124",
    Ammenities: "Accessible Shower, Accessible Entrance",
    Location: "Courchevel",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Gray",
    price: "194",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Centre",
    price: "67",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Toulouse",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rouen",
    price: "57",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rouen",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Pins",
    price: "66",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "La Rochelle",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bayonne",
    price: "89",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Bayonne",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Plage",
    price: "82",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "La Baule-Escoublac",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Meridien Etoile",
    price: "307",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Tours",
    price: "80",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Tours",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Clos des Vignes",
    price: "122",
    Ammenities: "Accessible Rooms, Braille Signage",
    Location: "Reims",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "301",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bordeaux",
    price: "70",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Bordeaux",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Avignon",
    price: "86",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Avignon",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rennes",
    price: "79",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rennes",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Majestic",
    price: "352",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Cannes",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Ritz",
    price: "351",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Aubiers",
    price: "70",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nantes",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Marais Paris",
    price: "220",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Saint Germain",
    price: "120",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Des Arts",
    price: "85",
    Ammenities: "Lift, Braille signage",
    Location: "Monte-Carlo",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Villa des Fleurs",
    price: "104",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Saint-Georges",
    price: "70",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Montpellier",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Sofitel",
    price: "279",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Villa Saxe Eiffel",
    price: "178",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Montpellier",
    price: "61",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Montpellier",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Saint-Paul",
    price: "85",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Appartements du Vieux Port",
    price: "96",
    Ammenities: "Accessible Rooms, Accessible Entrance",
    Location: "Marseille",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Des Arts",
    price: "99",
    Ammenities: "Lift, Braille signage",
    Location: "Monte-Carlo",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Paris",
    price: "190",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nantes",
    price: "52",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Nantes",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Lion d'Or",
    price: "83",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Bayeux",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Westminster",
    price: "235",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Marseille",
    price: "90",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Shower",
    Location: "Marseille",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Metropole",
    price: "206",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Monte-Carlo",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal-Riviera",
    price: "223",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite Rougemont",
    price: "187",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Tilleuls",
    price: "65",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Rennes",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Dijon",
    price: "65",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Dijon",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Clos des Vignes",
    price: "121",
    Ammenities: "Accessible Rooms, Braille Signage",
    Location: "Reims",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Moulin de la Forge",
    price: "102",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Bayeux",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Strasbourg",
    price: "77",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Strasbourg",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison du Bonheur",
    price: "75",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy-le-Vieux",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bristol",
    price: "411",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Jardins de Provence",
    price: "80",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Reims",
    price: "63",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Shower",
    Location: "Reims",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "312",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Mirande",
    price: "356",
    Ammenities: "Braille elevator, Guide Dogs Allowed",
    Location: "Avignon",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Dijon",
    price: "57",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Dijon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Mercure Lyon Centre Plaza",
    price: "175",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les 2 Alpes",
    price: "139",
    Ammenities: "Elevator, Accessible Rooms, Ramp",
    Location: "Les Deux Alpes",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Metropole",
    price: "220",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Monte-Carlo",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Monceau",
    price: "290",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pavillon",
    price: "280",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Carcassonne",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Sofitel",
    price: "280",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Globe et Cecil",
    price: "180",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Centre",
    price: "75",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Toulouse",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite Rougemont",
    price: "166",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Original Paris",
    price: "150",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lille",
    price: "60",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Lille",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Mirande",
    price: "348",
    Ammenities: "Braille elevator, Guide Dogs Allowed",
    Location: "Avignon",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bellechasse",
    price: "268",
    Ammenities: "Wheelchair Accessible Entrance, Ramp",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nantes",
    price: "66",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Nantes",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Saint-Malo",
    price: "93",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Saint-Malo",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton",
    price: "175",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Cannes",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Soleil",
    price: "71",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Havre",
    price: "80",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Le Havre",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel InterContinental",
    price: "285",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Marseille",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pavillon",
    price: "278",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Carcassonne",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Six",
    price: "237",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Reims",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les Jardins de La Villa",
    price: "315",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Paix",
    price: "112",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Reims",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Paris",
    price: "107",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel du Cap-Eden-Roc",
    price: "406",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Antibes",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Chateau Frontenac",
    price: "231",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Quebec",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Sofitel Lyon Bellecour",
    price: "304",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Carcassonne",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les Jardins de La Villa",
    price: "316",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Napoleon",
    price: "176",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Royal Lyon",
    price: "342",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel du Cap-Eden-Roc",
    price: "392",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Antibes",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Centre",
    price: "70",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Toulouse",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Majestic",
    price: "274",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Plaza Athenee",
    price: "389",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Antibes",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lyon",
    price: "95",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de la Plage",
    price: "69",
    Ammenities: "Accessible Entrance, Accessible Bathroom",
    Location: "Biarritz",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Suites de la Potini\u00c3\u00a8re",
    price: "129",
    Ammenities: "Accessible Shower, Accessible Entrance",
    Location: "Courchevel",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Meridien Etoile",
    price: "311",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Campanile",
    price: "68",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Saint-Malo",
    price: "90",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Saint-Malo",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite",
    price: "154",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Carcassonne",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Royal Lyon",
    price: "340",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Saules",
    price: "68",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton Lyon",
    price: "271",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les G\u00c3\u00aetes du Littoral",
    price: "94",
    Ammenities: "Accessible Rooms, Accessible Bathroom",
    Location: "Saint-Malo",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ormes",
    price: "71",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Tours",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ormes",
    price: "67",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Tours",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Caen",
    price: "64",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Caen",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bayonne",
    price: "99",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Bayonne",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Reims",
    price: "58",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Shower",
    Location: "Reims",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Pont",
    price: "85",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Bayonne",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Studios du Louvre",
    price: "73",
    Ammenities: "Accessible Bathroom, Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Original Paris",
    price: "155",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Monceau",
    price: "294",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bordeaux",
    price: "77",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Bordeaux",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison du Bonheur",
    price: "81",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy-le-Vieux",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Paris",
    price: "130",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel InterContinental",
    price: "262",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Marseille",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Villa Saxe Eiffel",
    price: "185",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Chateau Frontenac",
    price: "242",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Quebec",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Napoleon",
    price: "187",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les G\u00c3\u00aetes du Littoral",
    price: "76",
    Ammenities: "Accessible Rooms, Accessible Bathroom",
    Location: "Saint-Malo",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite Rougemont",
    price: "175",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Europe",
    price: "66",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Strasbourg",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Beau-Rivage",
    price: "179",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Appartements du Vieux Port",
    price: "98",
    Ammenities: "Accessible Rooms, Accessible Entrance",
    Location: "Marseille",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ecrins",
    price: "95",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Grenoble",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas des Oliviers",
    price: "96",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Crillon",
    price: "376",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Sofitel",
    price: "267",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Paris",
    price: "94",
    Ammenities: "Wheelchair Accessible Entrance, Elevator",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Tours",
    price: "71",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Tours",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pigalle",
    price: "242",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Ritz",
    price: "338",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Majestic",
    price: "354",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Cannes",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Metropole",
    price: "208",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Monte-Carlo",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Strasbourg",
    price: "79",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Strasbourg",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Metropole",
    price: "207",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Monte-Carlo",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas de la Garrigue",
    price: "100",
    Ammenities: "Wheelchair Accessible Entrance, Braille Signage",
    Location: "Arles",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Campanile",
    price: "80",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Havre",
    price: "77",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Le Havre",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Lyon",
    price: "99",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bayonne",
    price: "90",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Bayonne",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de L\u00c3\u00a9a",
    price: "74",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "N\u00c3\u00aemes",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Negresco",
    price: "263",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas de la Garrigue",
    price: "106",
    Ammenities: "Wheelchair Accessible Entrance, Braille Signage",
    Location: "Arles",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Crillon",
    price: "368",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ormes",
    price: "70",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Tours",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nantes",
    price: "60",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Nantes",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Abbaye",
    price: "173",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Ritz",
    price: "342",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Negresco",
    price: "268",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rouen",
    price: "70",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rouen",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Esprit Saint Germain",
    price: "401",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Maisons du Vieux Lille",
    price: "78",
    Ammenities: "Accessible Entrance, Braille Signage",
    Location: "Lille",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Elysee",
    price: "85",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Pavillon de la Rotonde",
    price: "217",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Saules",
    price: "81",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Annecy",
    price: "71",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Mercure",
    price: "121",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Bords de Mer",
    price: "95",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Marseille",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Trianon Rive Gauche",
    price: "229",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton",
    price: "173",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Cannes",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Novotel Lyon Centre Part Dieu",
    price: "203",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas des Oliviers",
    price: "92",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Sofitel",
    price: "280",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Mer",
    price: "76",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Malo",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Lyon",
    price: "105",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Antibes",
    price: "104",
    Ammenities: "Braille Signage, Accessible Bathroom",
    Location: "Antib",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Sofitel Lyon Bellecour",
    price: "300",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Carcassonne",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Villa des Fleurs",
    price: "90",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Soleil",
    price: "75",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Jardins de Provence",
    price: "94",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Mirande",
    price: "352",
    Ammenities: "Braille elevator, Guide Dogs Allowed",
    Location: "Avignon",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Paris",
    price: "100",
    Ammenities: "Wheelchair Accessible Entrance, Elevator",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Negresco",
    price: "261",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pavillon",
    price: "276",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Carcassonne",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Poitiers",
    price: "60",
    Ammenities: "Braille Signage, Visual Alarm/Alert in Guest Rooms",
    Location: "Poitiers",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Poitiers",
    price: "51",
    Ammenities: "Braille Signage, Visual Alarm/Alert in Guest Rooms",
    Location: "Poitiers",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Crillon",
    price: "371",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Plus Hotel Litteraire Alexandre Vialatte",
    price: "107",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Clermont-Ferrand",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Lyon",
    price: "94",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bellechasse",
    price: "284",
    Ammenities: "Wheelchair Accessible Entrance, Ramp",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Lion d'Or",
    price: "78",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Bayeux",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite",
    price: "142",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Carcassonne",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison du Bonheur",
    price: "87",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy-le-Vieux",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Des Arts",
    price: "85",
    Ammenities: "Lift, Braille signage",
    Location: "Monte-Carlo",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas des Oliviers",
    price: "100",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "306",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lille",
    price: "72",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Lille",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "304",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel InterContinental",
    price: "269",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Marseille",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Oliviers",
    price: "56",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Suites de la Potini\u00c3\u00a8re",
    price: "132",
    Ammenities: "Accessible Shower, Accessible Entrance",
    Location: "Courchevel",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bristol",
    price: "398",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Paris",
    price: "186",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Fouquet's Barriere",
    price: "360",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton Lyon",
    price: "280",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Avignon",
    price: "80",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Avignon",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Reims",
    price: "78",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Shower",
    Location: "Reims",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Plaza Athenee",
    price: "379",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Antibes",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton",
    price: "173",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Cannes",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lille",
    price: "55",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Lille",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bayonne",
    price: "84",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Bayonne",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Montpellier",
    price: "79",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Montpellier",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Am\u00c3\u00a9lie",
    price: "75",
    Ammenities: "Accessible Bathroom, Wheelchair Accessible Entrance",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Gray",
    price: "187",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal-Riviera",
    price: "243",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Monceau",
    price: "282",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lourdes",
    price: "99",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Bathroom",
    Location: "Lourdes",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Moulin de la Forge",
    price: "95",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Bayeux",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Beau-Rivage",
    price: "189",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Avignon",
    price: "95",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Avignon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Villa",
    price: "222",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Paris",
    price: "125",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Oliviers",
    price: "63",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bordeaux",
    price: "70",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Bordeaux",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Louvre Sainte Anne",
    price: "155",
    Ammenities: "Tactile signage, Accessible shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Paluds",
    price: "55",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Marseille",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Gray",
    price: "185",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "277",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de Jean",
    price: "90",
    Ammenities: "Accessible Shower, Accessible Rooms",
    Location: "Marseille",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Manoir des Roses",
    price: "126",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Versailles",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Manoir des Roses",
    price: "123",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Versailles",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas des Oliviers",
    price: "96",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Tours",
    price: "89",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Tours",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Toulouse",
    price: "89",
    Ammenities: "Wheelchair Accessible Bathroom, Accessible Entrance",
    Location: "Toulouse",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Caen",
    price: "66",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Caen",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Mercure Lyon Centre Plaza",
    price: "185",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Des Arts",
    price: "83",
    Ammenities: "Lift, Braille signage",
    Location: "Monte-Carlo",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Plus Hotel Litteraire Alexandre Vialatte",
    price: "89",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Clermont-Ferrand",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Villa Saxe Eiffel",
    price: "195",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Negresco",
    price: "263",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Toulouse",
    price: "80",
    Ammenities: "Wheelchair Accessible Bathroom, Accessible Entrance",
    Location: "Toulouse",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les 2 Alpes",
    price: "156",
    Ammenities: "Elevator, Accessible Rooms, Ramp",
    Location: "Les Deux Alpes",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Tilleuls",
    price: "61",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Rennes",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Meridien Etoile",
    price: "315",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Mercure",
    price: "128",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Paris",
    price: "88",
    Ammenities: "Wheelchair Accessible Entrance, Elevator",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Novotel Lyon Centre Part Dieu",
    price: "184",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Dijon",
    price: "59",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Dijon",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite Rougemont",
    price: "178",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel La Rochelle",
    price: "85",
    Ammenities: "Accessible Bathroom, Accessible Entrance",
    Location: "La Rochelle",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Fouquet's Barriere",
    price: "360",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Marseille",
    price: "87",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Shower",
    Location: "Marseille",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Paris",
    price: "100",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Pins",
    price: "69",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "La Rochelle",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Paix",
    price: "123",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Reims",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Pont",
    price: "84",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Bayonne",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Chambres de Charlotte",
    price: "59",
    Ammenities: "Wheelchair Accessible Parking, Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Elysee",
    price: "80",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Campanile",
    price: "82",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Lion d'Or",
    price: "85",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Bayeux",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Manoir des Roses",
    price: "120",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Versailles",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Grenoble",
    price: "65",
    Ammenities: "Braille Signage, Accessible Rooms",
    Location: "Grenoble",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lourdes",
    price: "100",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Bathroom",
    Location: "Lourdes",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Ang\u00c3\u00a8le",
    price: "73",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nantes",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Strasbourg",
    price: "89",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Strasbourg",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lyon",
    price: "85",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Maisons du Vieux Lille",
    price: "93",
    Ammenities: "Accessible Entrance, Braille Signage",
    Location: "Lille",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nice",
    price: "90",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Villa Saxe Eiffel",
    price: "186",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Montpellier",
    price: "72",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Montpellier",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Toulouse",
    price: "79",
    Ammenities: "Wheelchair Accessible Bathroom, Accessible Entrance",
    Location: "Toulouse",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Pins",
    price: "65",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "La Rochelle",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Globe et Cecil",
    price: "191",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Esprit Saint Germain",
    price: "390",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Mercure",
    price: "122",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Chambres de Charlotte",
    price: "60",
    Ammenities: "Wheelchair Accessible Parking, Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Crillon",
    price: "373",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel La Rochelle",
    price: "95",
    Ammenities: "Accessible Bathroom, Accessible Entrance",
    Location: "La Rochelle",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Louvre Sainte Anne",
    price: "152",
    Ammenities: "Tactile signage, Accessible shower",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Esprit Saint Germain",
    price: "388",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Studios du Louvre",
    price: "88",
    Ammenities: "Accessible Bathroom, Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Paix",
    price: "108",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Reims",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Gray",
    price: "185",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "288",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Elysee",
    price: "74",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rouen",
    price: "59",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rouen",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les Jardins de La Villa",
    price: "319",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Marais Paris",
    price: "215",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Havre",
    price: "80",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Le Havre",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Trianon Rive Gauche",
    price: "220",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Biarritz",
    price: "90",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Biarritz",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Paluds",
    price: "55",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Marseille",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "308",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rouen",
    price: "60",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rouen",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Mer",
    price: "72",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Malo",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Six",
    price: "245",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Reims",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Tilleuls",
    price: "77",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Rennes",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Globe et Cecil",
    price: "176",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Pavillon de la Rotonde",
    price: "226",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nantes",
    price: "68",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Nantes",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Biarritz",
    price: "90",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Biarritz",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Saint-Malo",
    price: "88",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Saint-Malo",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de Jean",
    price: "104",
    Ammenities: "Accessible Shower, Accessible Rooms",
    Location: "Marseille",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lyon",
    price: "84",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Paris",
    price: "197",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Saint-Paul",
    price: "79",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bellechasse",
    price: "270",
    Ammenities: "Wheelchair Accessible Entrance, Ramp",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison des Ch\u00c3\u00aanes",
    price: "101",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Bordeaux",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Pavillon de la Rotonde",
    price: "217",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Sofitel Lyon Bellecour",
    price: "295",
    Ammenities: "Braille signage, Guide Dogs Allowed",
    Location: "Carcassonne",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de Paris",
    price: "203",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Paluds",
    price: "56",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Marseille",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal-Riviera",
    price: "231",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Grenoble",
    price: "59",
    Ammenities: "Braille Signage, Accessible Rooms",
    Location: "Grenoble",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Bords de Mer",
    price: "96",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Marseille",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pigalle",
    price: "237",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Original Paris",
    price: "156",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Majestic",
    price: "345",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Cannes",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Plage",
    price: "82",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "La Baule-Escoublac",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Saint-Paul",
    price: "90",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton",
    price: "162",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Cannes",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ecrins",
    price: "101",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Grenoble",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Campanile",
    price: "70",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Saint-Malo",
    price: "85",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Saint-Malo",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Reims",
    price: "65",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Shower",
    Location: "Reims",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Hotel Charlemagne",
    price: "115",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Costes",
    price: "313",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Fouquet's Barriere",
    price: "355",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Chambres de Charlotte",
    price: "58",
    Ammenities: "Wheelchair Accessible Parking, Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Grenoble",
    price: "64",
    Ammenities: "Braille Signage, Accessible Rooms",
    Location: "Grenoble",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Mercure Lyon Centre Plaza",
    price: "170",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Suites de la Potini\u00c3\u00a8re",
    price: "120",
    Ammenities: "Accessible Shower, Accessible Entrance",
    Location: "Courchevel",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Marais Paris",
    price: "225",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nice",
    price: "98",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Le Pavillon de la Rotonde",
    price: "227",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Saint Germain",
    price: "116",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Caen",
    price: "55",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Caen",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Napoleon",
    price: "187",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Biarritz",
    price: "82",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Biarritz",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel du Cap-Eden-Roc",
    price: "409",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Antibes",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Plage",
    price: "87",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "La Baule-Escoublac",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bellechasse",
    price: "261",
    Ammenities: "Wheelchair Accessible Entrance, Ramp",
    Location: "Charbonni\u00c3\u00a8res-les-Bains",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Majestic",
    price: "260",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Majestic",
    price: "259",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Villa des Fleurs",
    price: "99",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Cite",
    price: "147",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Carcassonne",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ecrins",
    price: "90",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Grenoble",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Globe et Cecil",
    price: "172",
    Ammenities: "Guide Dogs Allowed, Accessible shower",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Saules",
    price: "64",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les 2 Alpes",
    price: "146",
    Ammenities: "Elevator, Accessible Rooms, Ramp",
    Location: "Les Deux Alpes",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Toulouse",
    price: "79",
    Ammenities: "Wheelchair Accessible Bathroom, Accessible Entrance",
    Location: "Toulouse",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lille",
    price: "52",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Lille",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Clos des Vignes",
    price: "117",
    Ammenities: "Accessible Rooms, Braille Signage",
    Location: "Reims",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel La Rochelle",
    price: "98",
    Ammenities: "Accessible Bathroom, Accessible Entrance",
    Location: "La Rochelle",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Barriere Le Majestic",
    price: "254",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "304",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas de la Garrigue",
    price: "110",
    Ammenities: "Wheelchair Accessible Entrance, Braille Signage",
    Location: "Arles",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Saint-Paul",
    price: "85",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal-Riviera",
    price: "224",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les G\u00c3\u00aetes du Littoral",
    price: "80",
    Ammenities: "Accessible Rooms, Accessible Bathroom",
    Location: "Saint-Malo",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Six",
    price: "243",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Reims",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Ang\u00c3\u00a8le",
    price: "83",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nantes",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de la Plage",
    price: "66",
    Ammenities: "Accessible Entrance, Accessible Bathroom",
    Location: "Biarritz",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Aubiers",
    price: "62",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nantes",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Marais Paris",
    price: "227",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Hotel Charlemagne",
    price: "126",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Am\u00c3\u00a9lie",
    price: "76",
    Ammenities: "Accessible Bathroom, Wheelchair Accessible Entrance",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Elysee",
    price: "93",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Costes",
    price: "291",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Novotel Lyon Centre Part Dieu",
    price: "190",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Bordeaux",
    price: "73",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Bordeaux",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Antibes",
    price: "95",
    Ammenities: "Braille Signage, Accessible Bathroom",
    Location: "Antib",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Mer",
    price: "77",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Malo",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de la Plage",
    price: "80",
    Ammenities: "Accessible Entrance, Accessible Bathroom",
    Location: "Biarritz",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Hotel Charlemagne",
    price: "108",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Saint Germain",
    price: "122",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Paris",
    price: "128",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Trianon Rive Gauche",
    price: "214",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Studios du Louvre",
    price: "89",
    Ammenities: "Accessible Bathroom, Visual Alarm/Alert in Guest Rooms",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Amandiers",
    price: "83",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Mer",
    price: "78",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Saint-Malo",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ecrins",
    price: "82",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Grenoble",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Antibes",
    price: "100",
    Ammenities: "Braille Signage, Accessible Bathroom",
    Location: "Antib",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les 2 Alpes",
    price: "154",
    Ammenities: "Elevator, Accessible Rooms, Ramp",
    Location: "Les Deux Alpes",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Soleil",
    price: "86",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de L\u00c3\u00a9a",
    price: "70",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "N\u00c3\u00aemes",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Villa",
    price: "230",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Les Jardins de La Villa",
    price: "315",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Europe",
    price: "69",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Strasbourg",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Westminster",
    price: "229",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lyon",
    price: "85",
    Ammenities: "Accessible Shower, Braille Signage",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Marseille",
    price: "85",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Shower",
    Location: "Marseille",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Montpellier",
    price: "70",
    Ammenities: "Accessible Parking, Accessible Rooms",
    Location: "Montpellier",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Novotel Lyon Centre Part Dieu",
    price: "204",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Plus Hotel Litteraire Alexandre Vialatte",
    price: "95",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Clermont-Ferrand",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Saint-Georges",
    price: "65",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Montpellier",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Grenoble",
    price: "75",
    Ammenities: "Braille Signage, Accessible Rooms",
    Location: "Grenoble",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "308",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Louvre Sainte Anne",
    price: "155",
    Ammenities: "Tactile signage, Accessible shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Nice",
    price: "98",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nice",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Beau-Rivage",
    price: "192",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Moulin de la Forge",
    price: "105",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Bayeux",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Marseille",
    price: "99",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Shower",
    Location: "Marseille",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Jardins de Provence",
    price: "88",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton Lyon",
    price: "292",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Royal Monceau",
    price: "301",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison du Bonheur",
    price: "72",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy-le-Vieux",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "274",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Mercure",
    price: "116",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bristol",
    price: "412",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Best Western Plus Hotel Litteraire Alexandre Vialatte",
    price: "96",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Clermont-Ferrand",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "271",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Villa",
    price: "219",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Paris",
    price: "119",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Paluds",
    price: "51",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Marseille",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Caen",
    price: "55",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "Caen",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "300",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Centre",
    price: "88",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Toulouse",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison des Ch\u00c3\u00aanes",
    price: "100",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Bordeaux",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Europe",
    price: "61",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "Strasbourg",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Appartements du Vieux Port",
    price: "87",
    Ammenities: "Accessible Rooms, Accessible Entrance",
    Location: "Marseille",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Saules",
    price: "79",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Royal Lyon",
    price: "335",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Am\u00c3\u00a9lie",
    price: "66",
    Ammenities: "Accessible Bathroom, Wheelchair Accessible Entrance",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Antibes",
    price: "101",
    Ammenities: "Braille Signage, Accessible Bathroom",
    Location: "Antib",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Appartements du Vieux Port",
    price: "85",
    Ammenities: "Accessible Rooms, Accessible Entrance",
    Location: "Marseille",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Amandiers",
    price: "72",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel de la Plage",
    price: "81",
    Ammenities: "Wheelchair Accessible Bathroom",
    Location: "La Baule-Escoublac",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Bristol",
    price: "397",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Paris",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Saint-Georges",
    price: "68",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Montpellier",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Abbaye",
    price: "160",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Regina",
    price: "310",
    Ammenities: "Accessible Parking, Braille signage",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pigalle",
    price: "237",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rennes",
    price: "80",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rennes",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Westminster",
    price: "240",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Chateau Frontenac",
    price: "229",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Quebec",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Maisons du Vieux Lille",
    price: "82",
    Ammenities: "Accessible Entrance, Braille Signage",
    Location: "Lille",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Am\u00c3\u00a9lie",
    price: "89",
    Ammenities: "Accessible Bathroom, Wheelchair Accessible Entrance",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Aubiers",
    price: "66",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Nantes",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de la Paix",
    price: "106",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Reims",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Fouquet's Barriere",
    price: "351",
    Ammenities: "Wheelchair Accessible Entrance",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Louvre Sainte Anne",
    price: "164",
    Ammenities: "Tactile signage, Accessible shower",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Esprit Saint Germain",
    price: "395",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison d'Ang\u00c3\u00a8le",
    price: "74",
    Ammenities: "Accessible Parking, Accessible Bathroom",
    Location: "Nantes",
    Links: "Link 2",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de la Plage",
    price: "70",
    Ammenities: "Accessible Entrance, Accessible Bathroom",
    Location: "Biarritz",
    Links: "Link 1",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Dijon",
    price: "71",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Dijon",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Soleil",
    price: "68",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Abbaye",
    price: "167",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Clos des Vignes",
    price: "110",
    Ammenities: "Accessible Rooms, Braille Signage",
    Location: "Reims",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Moulin de la Forge",
    price: "104",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Bayeux",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de L\u00c3\u00a9a",
    price: "76",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "N\u00c3\u00aemes",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Manoir des Roses",
    price: "123",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Versailles",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Annecy",
    price: "66",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pigalle",
    price: "240",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel du Pont",
    price: "90",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Bayonne",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Annecy",
    price: "73",
    Ammenities: "Accessible Parking, Wheelchair Accessible Entrance",
    Location: "Annecy",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Bords de Mer",
    price: "103",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Marseille",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Chateau Frontenac",
    price: "224",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Quebec",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rennes",
    price: "70",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rennes",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Chambres de Charlotte",
    price: "58",
    Ammenities: "Wheelchair Accessible Parking, Accessible Entrance",
    Location: "Strasbourg",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Ormes",
    price: "68",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Tours",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Six",
    price: "236",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Reims",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Beau-Rivage",
    price: "187",
    Ammenities: "Wheelchair Accessible Parking",
    Location: "Nice",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Ritz",
    price: "341",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Paris",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Lourdes",
    price: "96",
    Ammenities: "Wheelchair Accessible Entrance, Accessible Bathroom",
    Location: "Lourdes",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Paris",
    price: "93",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Paris",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Original Paris",
    price: "145",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de Jean",
    price: "90",
    Ammenities: "Accessible Shower, Accessible Rooms",
    Location: "Marseille",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Villa",
    price: "225",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Homestays",
    Accomodations: "Le Mas de la Garrigue",
    price: "99",
    Ammenities: "Wheelchair Accessible Entrance, Braille Signage",
    Location: "Arles",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel La Mirande",
    price: "359",
    Ammenities: "Braille elevator, Guide Dogs Allowed",
    Location: "Avignon",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Amandiers",
    price: "81",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Martinez",
    price: "306",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Cannes",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Rennes",
    price: "84",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Rennes",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Oliviers",
    price: "64",
    Ammenities: "Wheelchair Accessible Lobby",
    Location: "Nice",
    Links: "Link 4",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel de l'Abbaye",
    price: "152",
    Ammenities: "Accessible Parking, Elevator",
    Location: "Lyon",
    Links: "Link 2",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Strasbourg",
    price: "75",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Strasbourg",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Royal Lyon",
    price: "334",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Jardins de Provence",
    price: "85",
    Ammenities: "Wheelchair Accessible Parking, Accessible Rooms",
    Location: "Avignon",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Le Pavillon",
    price: "273",
    Ammenities: "Braille signage, Accessible shower",
    Location: "Carcassonne",
    Links: "Link 4",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Le Lion d'Or",
    price: "72",
    Ammenities: "Accessible Rooms, Elevator",
    Location: "Bayeux",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "La Maison de L\u00c3\u00a9a",
    price: "66",
    Ammenities: "Visual Alarm/Alert in Guest Rooms, Accessible Bathroom",
    Location: "N\u00c3\u00aemes",
    Links: "Link 3",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Bords de Mer",
    price: "103",
    Ammenities: "Braille Signage, Accessible Parking",
    Location: "Marseille",
    Links: "Link 2",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Paris",
    price: "90",
    Ammenities: "Wheelchair Accessible Entrance, Elevator",
    Location: "Paris",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel les Pins",
    price: "58",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "La Rochelle",
    Links: "Link 4",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Tours",
    price: "74",
    Ammenities: "Accessible Shower, Wheelchair Accessible Entrance",
    Location: "Tours",
    Links: "Link 2",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Carlton Lyon",
    price: "289",
    Ammenities: "Wheelchair Accessible Rooms, Ramp",
    Location: "Lyon",
    Links: "Link 4",
  },
  {
    Type: "Homestays",
    Accomodations: "Les Maisons du Vieux Lille",
    price: "85",
    Ammenities: "Accessible Entrance, Braille Signage",
    Location: "Lille",
    Links: "Link 1",
  },
  {
    Type: "Motel",
    Accomodations: "Motel Les Amandiers",
    price: "76",
    Ammenities: "Accessible Parking, Accessible Entrance",
    Location: "Aix-en-Provence",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Mama Shelter Lyon",
    price: "109",
    Ammenities: "Wheelchair Accessible Rooms, Lift",
    Location: "Lyon",
    Links: "Link 3",
  },
  {
    Type: "Zostel",
    Accomodations: "Zostel Poitiers",
    price: "53",
    Ammenities: "Braille Signage, Visual Alarm/Alert in Guest Rooms",
    Location: "Poitiers",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Westminster",
    price: "232",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Saint-Jean-Cap-Ferrat",
    Links: "Link 3",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Costes",
    price: "299",
    Ammenities: "Accessible Bathroom, Accessible Shower",
    Location: "Nice",
    Links: "Link 1",
  },
  {
    Type: "Hotel",
    Accomodations: "Hotel Plaza Athenee",
    price: "389",
    Ammenities: "Visual Alarm/Alert in Guest Rooms",
    Location: "Antibes",
    Links: "Link 4",
  },
];
