module.exports = [
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, In-flight medical assistance",
    arrival: "Paris",
    arrivalTime1: "10:45",
    arrivalTime2: "18:45",
    cost: "222",
    departure: "Berlin",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "2h 45m",
  },
  {
    airlines: "Air France",
    ammenities: "Braille safety cards, Priority boarding",
    arrival: "Nice",
    arrivalTime1: "12:45",
    arrivalTime2: "20:45",
    cost: "288",
    departure: "Frankfurt",
    departureTime1: "10:30",
    departureTime2: "18:30",
    duration: "2h 15m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Wheelchair assistance, In-flight medical assistance, Extra legroom, Sign language interpretation",
    arrival: "Marseille",
    arrivalTime1: "15:45",
    arrivalTime2: "23:45",
    cost: "178",
    departure: "Munich",
    departureTime1: "13:15",
    departureTime2: "21:15",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Visual and auditory aids, Extra legroom, Special seating arrangements, Special meals",
    arrival: "Lyon",
    arrivalTime1: "18:30",
    arrivalTime2: "02:30",
    cost: "149",
    departure: "Hamburg",
    departureTime1: "16:00",
    departureTime2: "00:00",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Special seating arrangements, Accessible check-in counters, In-flight medical assistance, Accessible lavatories, Braille safety cards",
    arrival: "Toulouse",
    arrivalTime1: "22:15",
    arrivalTime2: "06:15",
    cost: "113",
    departure: "Dusseldorf",
    departureTime1: "19:30",
    departureTime2: "03:30",
    duration: "2h 45m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Priority baggage handling, Wheelchair assistance, Special seating arrangements, Special meals, Sign language interpretation",
    arrival: "Bordeaux",
    arrivalTime1: "10:15",
    arrivalTime2: "18:15",
    cost: "166",
    departure: "Cologne",
    departureTime1: "07:45",
    departureTime2: "15:45",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "In-flight medical assistance, Priority boarding, Special seating arrangements",
    arrival: "Marseille",
    arrivalTime1: "12:30",
    arrivalTime2: "20:30",
    cost: "141",
    departure: "Berlin",
    departureTime1: "10:00",
    departureTime2: "18:00",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Sign language interpretation, Priority boarding, Priority baggage handling, Wheelchair assistance, Special seating arrangements",
    arrival: "Lyon",
    arrivalTime1: "13:45",
    arrivalTime2: "21:45",
    cost: "217",
    departure: "Munich",
    departureTime1: "11:15",
    departureTime2: "19:15",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Sign language interpretation, Wheelchair assistance, Extra legroom, Special seating arrangements, Special meals",
    arrival: "Nice",
    arrivalTime1: "17:00",
    arrivalTime2: "01:00",
    cost: "265",
    departure: "Hamburg",
    departureTime1: "14:30",
    departureTime2: "22:30",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Braille safety cards, Priority boarding, Visual and auditory aids, Special seating arrangements, In-flight medical assistance",
    arrival: "Paris",
    arrivalTime1: "20:00",
    arrivalTime2: "04:00",
    cost: "185",
    departure: "Frankfurt",
    departureTime1: "18:00",
    departureTime2: "02:00",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Priority boarding, Accessible lavatories, Wheelchair assistance, Special seating arrangements, Visual and auditory aids",
    arrival: "Toulouse",
    arrivalTime1: "23:00",
    arrivalTime2: "07:00",
    cost: "128",
    departure: "Cologne",
    departureTime1: "20:30",
    departureTime2: "04:30",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Priority boarding, Priority baggage handling, Wheelchair assistance, Special seating arrangements, In-flight medical assistance",
    arrival: "Marseille",
    arrivalTime1: "09:15",
    arrivalTime2: "17:15",
    cost: "172",
    departure: "Stuttgart",
    departureTime1: "06:45",
    departureTime2: "14:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible check-in counters, In-flight medical assistance, Visual and auditory aids, Sign language interpretation, Braille safety cards",
    arrival: "Nice",
    arrivalTime1: "11:30",
    arrivalTime2: "19:30",
    cost: "237",
    departure: "Dusseldorf",
    departureTime1: "09:00",
    departureTime2: "17:00",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Special seating arrangements, Visual and auditory aids, Accessible lavatories, Sign language interpretation, In-flight medical assistance",
    arrival: "Lyon",
    arrivalTime1: "14:30",
    arrivalTime2: "22:30",
    cost: "208",
    departure: "Berlin",
    departureTime1: "12:00",
    departureTime2: "20:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Priority boarding, Braille safety cards",
    arrival: "Bordeaux",
    arrivalTime1: "17:45",
    arrivalTime2: "01:45",
    cost: "167",
    departure: "Munich",
    departureTime1: "15:15",
    departureTime2: "23:15",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities: "Accessible check-in counters, Extra legroom",
    arrival: "Toulouse",
    arrivalTime1: "20:15",
    arrivalTime2: "04:15",
    cost: "117",
    departure: "Frankfurt",
    departureTime1: "17:30",
    departureTime2: "01:30",
    duration: "2h 45m",
  },
  {
    airlines: "EasyJet",
    ammenities: "Visual and auditory aids, Special meals",
    arrival: "Marseille",
    arrivalTime1: "22:30",
    arrivalTime2: "06:30",
    cost: "166",
    departure: "Hamburg",
    departureTime1: "20:00",
    departureTime2: "04:00",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Accessible check-in counters, Special meals, Extra legroom, In-flight medical assistance, Accessible lavatories",
    arrival: "Lyon",
    arrivalTime1: "11:00",
    arrivalTime2: "19:00",
    cost: "249",
    departure: "Dusseldorf",
    departureTime1: "08:30",
    departureTime2: "16:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "In-flight medical assistance, Accessible lavatories",
    arrival: "Nice",
    arrivalTime1: "14:00",
    arrivalTime2: "22:00",
    cost: "214",
    departure: "Berlin",
    departureTime1: "11:30",
    departureTime2: "19:30",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Extra legroom, Special seating arrangements",
    arrival: "Toulouse",
    arrivalTime1: "17:15",
    arrivalTime2: "01:15",
    cost: "151",
    departure: "Stuttgart",
    departureTime1: "14:45",
    departureTime2: "22:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Sign language interpretation, Accessible check-in counters, Accessible lavatories",
    arrival: "Marseille",
    arrivalTime1: "09:00",
    arrivalTime2: "17:00",
    cost: "248",
    departure: "Frankfurt",
    departureTime1: "06:30",
    departureTime2: "14:30",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Accessible check-in counters, Sign language interpretation, Priority baggage handling, Special meals, Extra legroom",
    arrival: "Toulouse",
    arrivalTime1: "11:45",
    arrivalTime2: "19:45",
    cost: "216",
    departure: "Berlin",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Accessible check-in counters, Priority baggage handling, Braille safety cards, Special meals",
    arrival: "Bordeaux",
    arrivalTime1: "14:30",
    arrivalTime2: "22:30",
    cost: "165",
    departure: "Hamburg",
    departureTime1: "12:00",
    departureTime2: "20:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Priority baggage handling, Extra legroom",
    arrival: "Nice",
    arrivalTime1: "17:15",
    arrivalTime2: "01:15",
    cost: "177",
    departure: "Munich",
    departureTime1: "15:15",
    departureTime2: "23:15",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Priority boarding, Special seating arrangements, Visual and auditory aids, Wheelchair assistance",
    arrival: "Paris",
    arrivalTime1: "20:45",
    arrivalTime2: "04:45",
    cost: "109",
    departure: "Cologne",
    departureTime1: "18:45",
    departureTime2: "02:45",
    duration: "2h",
  },
  {
    airlines: "Air France",
    ammenities: "Sign language interpretation, Accessible check-in counters",
    arrival: "Marseille",
    arrivalTime1: "00:45",
    arrivalTime2: "08:45",
    cost: "270",
    departure: "Dusseldorf",
    departureTime1: "22:30",
    departureTime2: "06:30",
    duration: "2h 15m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Priority baggage handling, Priority boarding, Special seating arrangements, Braille safety cards, In-flight medical assistance",
    arrival: "Nice",
    arrivalTime1: "10:00",
    arrivalTime2: "18:00",
    cost: "162",
    departure: "Berlin",
    departureTime1: "07:30",
    departureTime2: "15:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible check-in counters, Sign language interpretation, Priority baggage handling, In-flight medical assistance",
    arrival: "Lyon",
    arrivalTime1: "12:45",
    arrivalTime2: "20:45",
    cost: "233",
    departure: "Frankfurt",
    departureTime1: "10:15",
    departureTime2: "18:15",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Special meals, Accessible check-in counters, Braille safety cards",
    arrival: "Toulouse",
    arrivalTime1: "16:15",
    arrivalTime2: "00:15",
    cost: "161",
    departure: "Munich",
    departureTime1: "13:45",
    departureTime2: "21:45",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Extra legroom, In-flight medical assistance, Sign language interpretation, Special meals",
    arrival: "Marseille",
    arrivalTime1: "18:45",
    arrivalTime2: "02:45",
    cost: "120",
    departure: "Hamburg",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "2h 15m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Special meals, Priority boarding, In-flight medical assistance, Braille safety cards",
    arrival: "Bordeaux",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "203",
    departure: "Cologne",
    departureTime1: "19:00",
    departureTime2: "03:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Extra legroom, Visual and auditory aids",
    arrival: "Nice",
    arrivalTime1: "11:00",
    arrivalTime2: "19:00",
    cost: "191",
    departure: "Stuttgart",
    departureTime1: "08:45",
    departureTime2: "16:45",
    duration: "2h 15m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Braille safety cards, Accessible check-in counters, Special meals, Sign language interpretation",
    arrival: "Paris",
    arrivalTime1: "13:30",
    arrivalTime2: "21:30",
    cost: "131",
    departure: "Dusseldorf",
    departureTime1: "11:30",
    departureTime2: "19:30",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Visual and auditory aids, Priority baggage handling, Extra legroom",
    arrival: "Toulouse",
    arrivalTime1: "16:30",
    arrivalTime2: "00:30",
    cost: "149",
    departure: "Berlin",
    departureTime1: "14:00",
    departureTime2: "22:00",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, Special meals, Accessible check-in counters",
    arrival: "Bordeaux",
    arrivalTime1: "20:15",
    arrivalTime2: "04:15",
    cost: "219",
    departure: "Munich",
    departureTime1: "17:45",
    departureTime2: "01:45",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities: "Braille safety cards, Accessible lavatories, Extra legroom",
    arrival: "Marseille",
    arrivalTime1: "22:30",
    arrivalTime2: "06:30",
    cost: "250",
    departure: "Frankfurt",
    departureTime1: "20:00",
    departureTime2: "04:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Special meals, Braille safety cards",
    arrival: "Nice",
    arrivalTime1: "09:15",
    arrivalTime2: "17:15",
    cost: "159",
    departure: "Hamburg",
    departureTime1: "07:15",
    departureTime2: "15:15",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Accessible check-in counters, Priority baggage handling, Extra legroom, Special seating arrangements, Accessible lavatories",
    arrival: "Lyon",
    arrivalTime1: "12:30",
    arrivalTime2: "20:30",
    cost: "125",
    departure: "Cologne",
    departureTime1: "10:00",
    departureTime2: "18:00",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Accessible check-in counters, Priority baggage handling, Sign language interpretation, Wheelchair assistance",
    arrival: "Toulouse",
    arrivalTime1: "15:45",
    arrivalTime2: "23:45",
    cost: "161",
    departure: "Stuttgart",
    departureTime1: "13:15",
    departureTime2: "21:15",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Accessible lavatories, Sign language interpretation, Accessible check-in counters, Visual and auditory aids, Braille safety cards",
    arrival: "Bordeaux",
    arrivalTime1: "19:00",
    arrivalTime2: "03:00",
    cost: "244",
    departure: "Dusseldorf",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities: "Priority baggage handling, Extra legroom",
    arrival: "Nice",
    arrivalTime1: "08:00",
    arrivalTime2: "16:00",
    cost: "207",
    departure: "Munich",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "2h",
  },
  {
    airlines: "Eurowings",
    ammenities: "Braille safety cards, Priority boarding",
    arrival: "Bordeaux",
    arrivalTime1: "12:00",
    arrivalTime2: "20:00",
    cost: "163",
    departure: "Berlin",
    departureTime1: "09:30",
    departureTime2: "17:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Priority baggage handling, Braille safety cards, Special seating arrangements, Visual and auditory aids, Priority boarding",
    arrival: "Lyon",
    arrivalTime1: "14:45",
    arrivalTime2: "22:45",
    cost: "231",
    departure: "Frankfurt",
    departureTime1: "12:15",
    departureTime2: "20:15",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Priority baggage handling, Priority boarding, Visual and auditory aids, Special meals",
    arrival: "Toulouse",
    arrivalTime1: "17:30",
    arrivalTime2: "01:30",
    cost: "146",
    departure: "Hamburg",
    departureTime1: "15:00",
    departureTime2: "23:00",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Sign language interpretation, Visual and auditory aids, Accessible lavatories, Braille safety cards",
    arrival: "Marseille",
    arrivalTime1: "20:15",
    arrivalTime2: "04:15",
    cost: "139",
    departure: "Stuttgart",
    departureTime1: "18:15",
    departureTime2: "02:15",
    duration: "2h",
  },
  {
    airlines: "Air France",
    ammenities: "Accessible check-in counters, Extra legroom",
    arrival: "Nice",
    arrivalTime1: "23:30",
    arrivalTime2: "07:30",
    cost: "240",
    departure: "Cologne",
    departureTime1: "21:30",
    departureTime2: "05:30",
    duration: "2h",
  },
  {
    airlines: "Eurowings",
    ammenities: "Priority baggage handling, Visual and auditory aids",
    arrival: "Bordeaux",
    arrivalTime1: "10:15",
    arrivalTime2: "18:15",
    cost: "183",
    departure: "Dusseldorf",
    departureTime1: "07:45",
    departureTime2: "15:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Special meals, Accessible lavatories, Extra legroom",
    arrival: "Toulouse",
    arrivalTime1: "13:00",
    arrivalTime2: "21:00",
    cost: "256",
    departure: "Munich",
    departureTime1: "10:30",
    departureTime2: "18:30",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "In-flight medical assistance, Sign language interpretation, Special meals, Braille safety cards",
    arrival: "Marseille",
    arrivalTime1: "15:45",
    arrivalTime2: "23:45",
    cost: "138",
    departure: "Berlin",
    departureTime1: "13:15",
    departureTime2: "21:15",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Extra legroom, Priority baggage handling, Sign language interpretation, Special seating arrangements, Priority boarding",
    arrival: "Nice",
    arrivalTime1: "18:00",
    arrivalTime2: "02:00",
    cost: "145",
    departure: "Frankfurt",
    departureTime1: "16:00",
    departureTime2: "00:00",
    duration: "2h",
  },
  {
    airlines: "Air France",
    ammenities:
      "Visual and auditory aids, Special seating arrangements, Priority boarding, Braille safety cards",
    arrival: "Lyon",
    arrivalTime1: "21:45",
    arrivalTime2: "05:45",
    cost: "211",
    departure: "Hamburg",
    departureTime1: "19:15",
    departureTime2: "03:15",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Extra legroom, Visual and auditory aids, Priority baggage handling, Sign language interpretation, Braille safety cards",
    arrival: "Toulouse",
    arrivalTime1: "00:30",
    arrivalTime2: "08:30",
    cost: "177",
    departure: "Cologne",
    departureTime1: "22:00",
    departureTime2: "06:00",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities: "Accessible check-in counters, Visual and auditory aids",
    arrival: "Bordeaux",
    arrivalTime1: "10:00",
    arrivalTime2: "18:00",
    cost: "133",
    departure: "Stuttgart",
    departureTime1: "07:30",
    departureTime2: "15:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible lavatories, Priority boarding, Sign language interpretation, Special seating arrangements",
    arrival: "Nice",
    arrivalTime1: "12:15",
    arrivalTime2: "20:15",
    cost: "197",
    departure: "Dusseldorf",
    departureTime1: "10:15",
    departureTime2: "18:15",
    duration: "2h",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Special seating arrangements, Braille safety cards, Visual and auditory aids, Special meals, Extra legroom",
    arrival: "Lyon",
    arrivalTime1: "16:15",
    arrivalTime2: "00:15",
    cost: "162",
    departure: "Munich",
    departureTime1: "13:45",
    departureTime2: "21:45",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Priority boarding, Visual and auditory aids, Sign language interpretation, Accessible check-in counters",
    arrival: "Marseille",
    arrivalTime1: "19:00",
    arrivalTime2: "03:00",
    cost: "230",
    departure: "Berlin",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Extra legroom, Priority boarding, Priority baggage handling",
    arrival: "Toulouse",
    arrivalTime1: "22:15",
    arrivalTime2: "06:15",
    cost: "180",
    departure: "Frankfurt",
    departureTime1: "19:45",
    departureTime2: "03:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible lavatories, Priority boarding, Visual and auditory aids",
    arrival: "Nice",
    arrivalTime1: "08:00",
    arrivalTime2: "16:00",
    cost: "217",
    departure: "Hamburg",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Accessible check-in counters, Wheelchair assistance, Sign language interpretation",
    arrival: "Marseille",
    arrivalTime1: "11:45",
    arrivalTime2: "19:45",
    cost: "154",
    departure: "Cologne",
    departureTime1: "09:30",
    departureTime2: "17:30",
    duration: "2h 15m",
  },
  {
    airlines: "EasyJet",
    ammenities: "Visual and auditory aids, Sign language interpretation",
    arrival: "Lyon",
    arrivalTime1: "14:30",
    arrivalTime2: "22:30",
    cost: "167",
    departure: "Dusseldorf",
    departureTime1: "12:00",
    departureTime2: "20:00",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Accessible check-in counters, Special meals, Braille safety cards, Sign language interpretation",
    arrival: "Paris",
    arrivalTime1: "10:45",
    arrivalTime2: "18:45",
    cost: "221",
    departure: "Berlin",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "2h 45m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Sign language interpretation, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime1: "11:30",
    arrivalTime2: "19:30",
    cost: "987",
    departure: "Toronto",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Accessible lavatories, Accessible check-in counters",
    arrival: "Frankfurt",
    arrivalTime1: "16:30",
    arrivalTime2: "00:30",
    cost: "1091",
    departure: "Montreal",
    departureTime1: "12:15",
    departureTime2: "20:15",
    duration: "9h 15m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Special seating arrangements, Braille safety cards, Priority baggage handling",
    arrival: "Hamburg",
    arrivalTime1: "19:30",
    arrivalTime2: "03:30",
    cost: "887",
    departure: "Vancouver",
    departureTime1: "15:00",
    departureTime2: "23:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Sign language interpretation, Braille safety cards, Priority baggage handling, Extra legroom, Visual and auditory aids",
    arrival: "Cologne",
    arrivalTime1: "03:00",
    arrivalTime2: "11:00",
    cost: "791",
    departure: "Calgary",
    departureTime1: "21:30",
    departureTime2: "05:30",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Wheelchair assistance, Accessible lavatories, Extra legroom",
    arrival: "Dusseldorf",
    arrivalTime1: "11:00",
    arrivalTime2: "19:00",
    cost: "1027",
    departure: "Toronto",
    departureTime1: "07:45",
    departureTime2: "15:45",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Priority baggage handling, Extra legroom, Accessible check-in counters",
    arrival: "Munich",
    arrivalTime1: "15:00",
    arrivalTime2: "23:00",
    cost: "1121",
    departure: "Montreal",
    departureTime1: "10:30",
    departureTime2: "18:30",
    duration: "8h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Accessible lavatories, Priority boarding",
    arrival: "Berlin",
    arrivalTime1: "17:45",
    arrivalTime2: "01:45",
    cost: "953",
    departure: "Vancouver",
    departureTime1: "13:15",
    departureTime2: "21:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Accessible check-in counters, Priority baggage handling",
    arrival: "Frankfurt",
    arrivalTime1: "22:30",
    arrivalTime2: "06:30",
    cost: "845",
    departure: "Calgary",
    departureTime1: "16:00",
    departureTime2: "00:00",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Priority boarding, In-flight medical assistance",
    arrival: "Hamburg",
    arrivalTime1: "22:30",
    arrivalTime2: "06:30",
    cost: "1012",
    departure: "Toronto",
    departureTime1: "19:15",
    departureTime2: "03:15",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Visual and auditory aids, Braille safety cards, Accessible lavatories",
    arrival: "Cologne",
    arrivalTime1: "02:30",
    arrivalTime2: "10:30",
    cost: "1084",
    departure: "Montreal",
    departureTime1: "22:00",
    departureTime2: "06:00",
    duration: "9h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Visual and auditory aids, Accessible check-in counters, Braille safety cards",
    arrival: "Dusseldorf",
    arrivalTime1: "12:00",
    arrivalTime2: "20:00",
    cost: "930",
    departure: "Vancouver",
    departureTime1: "07:30",
    departureTime2: "15:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Priority baggage handling, Special meals",
    arrival: "Munich",
    arrivalTime1: "16:45",
    arrivalTime2: "00:45",
    cost: "828",
    departure: "Calgary",
    departureTime1: "10:15",
    departureTime2: "18:15",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Braille safety cards, Priority boarding, Special meals, Priority baggage handling, Accessible lavatories",
    arrival: "Berlin",
    arrivalTime1: "17:00",
    arrivalTime2: "01:00",
    cost: "1042",
    departure: "Toronto",
    departureTime1: "13:45",
    departureTime2: "21:45",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Extra legroom, Priority baggage handling, Braille safety cards, Wheelchair assistance, Sign language interpretation",
    arrival: "Frankfurt",
    arrivalTime1: "21:00",
    arrivalTime2: "05:00",
    cost: "1163",
    departure: "Vancouver",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "9h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Sign language interpretation, Priority boarding, In-flight medical assistance",
    arrival: "Hamburg",
    arrivalTime1: "12:30",
    arrivalTime2: "20:30",
    cost: "900",
    departure: "Calgary",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Braille safety cards, Extra legroom",
    arrival: "Cologne",
    arrivalTime1: "13:45",
    arrivalTime2: "21:45",
    cost: "1037",
    departure: "Toronto",
    departureTime1: "09:30",
    departureTime2: "17:30",
    duration: "9h 15m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Special seating arrangements, Visual and auditory aids, Priority boarding",
    arrival: "Dusseldorf",
    arrivalTime1: "16:30",
    arrivalTime2: "00:30",
    cost: "971",
    departure: "Montreal",
    departureTime1: "12:00",
    departureTime2: "20:00",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Priority boarding, In-flight medical assistance, Priority baggage handling, Accessible check-in counters",
    arrival: "Munich",
    arrivalTime1: "22:00",
    arrivalTime2: "06:00",
    cost: "1092",
    departure: "Vancouver",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "10h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Accessible check-in counters, Extra legroom, Braille safety cards, Priority baggage handling",
    arrival: "Berlin",
    arrivalTime1: "02:15",
    arrivalTime2: "10:15",
    cost: "880",
    departure: "Calgary",
    departureTime1: "19:45",
    departureTime2: "03:45",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Special meals, Special seating arrangements, Extra legroom, Wheelchair assistance, Priority baggage handling",
    arrival: "Frankfurt",
    arrivalTime1: "02:15",
    arrivalTime2: "10:15",
    cost: "",
    departure: "Toronto",
    departureTime1: "22:00",
    departureTime2: "06:00",
    duration: "8h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "In-flight medical assistance, Accessible lavatories",
    arrival: "rankfurt",
    arrivalTime1: "13:30",
    arrivalTime2: "21:30",
    cost: "1187",
    departure: "Ottawa",
    departureTime1: "08:30",
    departureTime2: "16:30",
    duration: "9h 00m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Braille safety cards, Special meals, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime1: "18:15",
    arrivalTime2: "02:15",
    cost: "1098",
    departure: "Edmonton",
    departureTime1: "11:45",
    departureTime2: "19:45",
    duration: "10h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "In-flight medical assistance, Extra legroom, Special meals, Priority boarding",
    arrival: "Dusseldorf",
    arrivalTime1: "19:30",
    arrivalTime2: "03:30",
    cost: "998",
    departure: "Halifax",
    departureTime1: "15:00",
    departureTime2: "23:00",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Priority boarding, In-flight medical assistance",
    arrival: "Munich",
    arrivalTime1: "00:15",
    arrivalTime2: "08:15",
    cost: "887",
    departure: "Vancouver",
    departureTime1: "18:45",
    departureTime2: "02:45",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, Accessible check-in counters",
    arrival: "Hamburg",
    arrivalTime1: "12:45",
    arrivalTime2: "20:45",
    cost: "1153",
    departure: "Montreal",
    departureTime1: "08:15",
    departureTime2: "16:15",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Wheelchair assistance, Priority baggage handling, Visual and auditory aids",
    arrival: "Cologne",
    arrivalTime1: "15:45",
    arrivalTime2: "23:45",
    cost: "1060",
    departure: "Toronto",
    departureTime1: "11:30",
    departureTime2: "19:30",
    duration: "9h 15m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Accessible lavatories, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime1: "18:30",
    arrivalTime2: "02:30",
    cost: "1028",
    departure: "Halifax",
    departureTime1: "14:00",
    departureTime2: "22:00",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special meals, Wheelchair assistance, Accessible lavatories, Priority boarding, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime1: "22:00",
    arrivalTime2: "06:00",
    cost: "1021",
    departure: "Calgary",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Accessible lavatories, Wheelchair assistance",
    arrival: "Dusseldorf",
    arrivalTime1: "01:45",
    arrivalTime2: "09:45",
    cost: "938",
    departure: "Edmonton",
    departureTime1: "19:15",
    departureTime2: "03:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Visual and auditory aids, In-flight medical assistance, Special seating arrangements",
    arrival: "Munich",
    arrivalTime1: "10:45",
    arrivalTime2: "18:45",
    cost: "1169",
    departure: "Toronto",
    departureTime1: "06:30",
    departureTime2: "14:30",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime1: "14:30",
    arrivalTime2: "22:30",
    cost: "1111",
    departure: "Vancouver",
    departureTime1: "10:00",
    departureTime2: "18:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Wheelchair assistance, Special meals, Sign language interpretation",
    arrival: "Cologne",
    arrivalTime1: "18:15",
    arrivalTime2: "02:15",
    cost: "1058",
    departure: "Montreal",
    departureTime1: "13:45",
    departureTime2: "21:45",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Accessible lavatories, Special meals, Priority boarding",
    arrival: "Berlin",
    arrivalTime1: "21:00",
    arrivalTime2: "05:00",
    cost: "1081",
    departure: "Ottawa",
    departureTime1: "16:30",
    departureTime2: "00:30",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special meals, Visual and auditory aids",
    arrival: "Frankfurt",
    arrivalTime1: "02:15",
    arrivalTime2: "10:15",
    cost: "942",
    departure: "Edmonton",
    departureTime1: "19:45",
    departureTime2: "03:45",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Special meals, Sign language interpretation, Extra legroom",
    arrival: "Dusseldorf",
    arrivalTime1: "12:30",
    arrivalTime2: "20:30",
    cost: "1020",
    departure: "Vancouver",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "10h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Accessible lavatories, Visual and auditory aids",
    arrival: "Munich",
    arrivalTime1: "15:45",
    arrivalTime2: "23:45",
    cost: "1064",
    departure: "Halifax",
    departureTime1: "11:15",
    departureTime2: "19:15",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "In-flight medical assistance, Priority boarding, Special meals",
    arrival: "Hamburg",
    arrivalTime1: "22:15",
    arrivalTime2: "06:15",
    cost: "941",
    departure: "Calgary",
    departureTime1: "15:45",
    departureTime2: "23:45",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Priority boarding, Sign language interpretation",
    arrival: "Cologne",
    arrivalTime1: "22:30",
    arrivalTime2: "06:30",
    cost: "1082",
    departure: "Vancouver",
    departureTime1: "18:00",
    departureTime2: "02:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Priority baggage handling, Extra legroom, Visual and auditory aids, Sign language interpretation, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime1: "11:45",
    arrivalTime2: "19:45",
    cost: "1161",
    departure: "Toronto",
    departureTime1: "07:30",
    departureTime2: "15:30",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Accessible lavatories, Sign language interpretation, Priority boarding",
    arrival: "Frankfurt",
    arrivalTime1: "14:45",
    arrivalTime2: "22:45",
    cost: "1220",
    departure: "Montreal",
    departureTime1: "10:15",
    departureTime2: "18:15",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Braille safety cards, Visual and auditory aids, Extra legroom",
    arrival: "Hamburg",
    arrivalTime1: "16:00",
    arrivalTime2: "00:00",
    cost: "1099",
    departure: "Edmonton",
    departureTime1: "09:30",
    departureTime2: "17:30",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Extra legroom, Priority boarding",
    arrival: "Cologne",
    arrivalTime1: "17:30",
    arrivalTime2: "01:30",
    cost: "1043",
    departure: "Calgary",
    departureTime1: "12:00",
    departureTime2: "20:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Wheelchair assistance, Special seating arrangements, Priority baggage handling, Visual and auditory aids",
    arrival: "Berlin",
    arrivalTime1: "21:45",
    arrivalTime2: "05:45",
    cost: "932",
    departure: "Vancouver",
    departureTime1: "15:15",
    departureTime2: "23:15",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special seating arrangements, Accessible check-in counters",
    arrival: "Frankfurt",
    arrivalTime1: "22:45",
    arrivalTime2: "06:45",
    cost: "1112",
    departure: "Toronto",
    departureTime1: "18:30",
    departureTime2: "02:30",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Special seating arrangements, Braille safety cards, Extra legroom, Accessible lavatories, Special meals",
    arrival: "Dusseldorf",
    arrivalTime1: "01:30",
    arrivalTime2: "09:30",
    cost: "1152",
    departure: "Halifax",
    departureTime1: "21:00",
    departureTime2: "05:00",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "In-flight medical assistance, Priority baggage handling, Special meals, Braille safety cards, Extra legroom",
    arrival: "Munich",
    arrivalTime1: "14:15",
    arrivalTime2: "22:15",
    cost: "1035",
    departure: "Edmonton",
    departureTime1: "07:45",
    departureTime2: "15:45",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special meals, Extra legroom, Visual and auditory aids, Accessible lavatories, Accessible check-in counters",
    arrival: "Hamburg",
    arrivalTime1: "16:45",
    arrivalTime2: "00:45",
    cost: "1060",
    departure: "Calgary",
    departureTime1: "11:15",
    departureTime2: "19:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Accessible check-in counters, Priority boarding",
    arrival: "Cologne",
    arrivalTime1: "19:00",
    arrivalTime2: "03:00",
    cost: "988",
    departure: "Vancouver",
    departureTime1: "14:30",
    departureTime2: "22:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Visual and auditory aids, Accessible lavatories, Sign language interpretation",
    arrival: "Berlin",
    arrivalTime1: "21:15",
    arrivalTime2: "05:15",
    cost: "1100",
    departure: "Toronto",
    departureTime1: "17:00",
    departureTime2: "01:00",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Sign language interpretation, Priority boarding, Braille safety cards, Special seating arrangements",
    arrival: "Frankfurt",
    arrivalTime1: "01:15",
    arrivalTime2: "09:15",
    cost: "1175",
    departure: "Halifax",
    departureTime1: "20:45",
    departureTime2: "04:45",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Extra legroom, Accessible lavatories, In-flight medical assistance",
    arrival: "Dusseldorf",
    arrivalTime1: "14:00",
    arrivalTime2: "22:00",
    cost: "1043",
    departure: "Vancouver",
    departureTime1: "09:30",
    departureTime2: "17:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Priority boarding, Extra legroom",
    arrival: "Munich",
    arrivalTime1: "18:30",
    arrivalTime2: "02:30",
    cost: "1135",
    departure: "Calgary",
    departureTime1: "13:00",
    departureTime2: "21:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Priority boarding, Priority baggage handling, In-flight medical assistance, Braille safety cards",
    arrival: "Hamburg",
    arrivalTime1: "20:30",
    arrivalTime2: "04:30",
    cost: "1158",
    departure: "Toronto",
    departureTime1: "16:15",
    departureTime2: "00:15",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Priority baggage handling, Priority boarding, Extra legroom",
    arrival: "Cologne",
    arrivalTime1: "00:00",
    arrivalTime2: "08:00",
    cost: "1020",
    departure: "Halifax",
    departureTime1: "19:30",
    departureTime2: "03:30",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Wheelchair assistance, Visual and auditory aids, In-flight medical assistance",
    arrival: "Berlin",
    arrivalTime1: "04:30",
    arrivalTime2: "12:30",
    cost: "1061",
    departure: "Edmonton",
    departureTime1: "22:00",
    departureTime2: "06:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Priority baggage handling, Special meals, Braille safety cards, Wheelchair assistance, Special seating arrangements",
    arrival: "Frankfurt",
    arrivalTime1: "13:15",
    arrivalTime2: "21:15",
    cost: "975",
    departure: "Calgary",
    departureTime1: "06:45",
    departureTime2: "14:45",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Sign language interpretation, Special seating arrangements, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime1: "14:45",
    arrivalTime2: "22:45",
    cost: "1121",
    departure: "Toronto",
    departureTime1: "10:30",
    departureTime2: "18:30",
    duration: "9h 15m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Special seating arrangements, Accessible check-in counters, Sign language interpretation, Wheelchair assistance",
    arrival: "Munich",
    arrivalTime1: "18:30",
    arrivalTime2: "02:30",
    cost: "995",
    departure: "Halifax",
    departureTime1: "14:00",
    departureTime2: "22:00",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Visual and auditory aids, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime1: "21:45",
    arrivalTime2: "05:45",
    cost: "1116",
    departure: "Vancouver",
    departureTime1: "17:15",
    departureTime2: "01:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Accessible check-in counters, Wheelchair assistance",
    arrival: "Cologne",
    arrivalTime1: "00:45",
    arrivalTime2: "08:45",
    cost: "1040",
    departure: "Toronto",
    departureTime1: "20:30",
    departureTime2: "04:30",
    duration: "9h 15m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Visual and auditory aids, Special meals, Sign language interpretation, Priority baggage handling, Accessible check-in counters",
    arrival: "Munich",
    arrivalTime1: "19:00",
    arrivalTime2: "03:00",
    cost: "940",
    departure: "Dubai",
    departureTime1: "10:00",
    departureTime2: "18:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Accessible lavatories, Wheelchair assistance, Braille safety cards, Sign language interpretation",
    arrival: "Frankfurt",
    arrivalTime1: "22:30",
    arrivalTime2: "06:30",
    cost: "1025",
    departure: "Abu Dhabi",
    departureTime1: "13:30",
    departureTime2: "21:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Special seating arrangements, Accessible lavatories, Priority boarding",
    arrival: "Berlin",
    arrivalTime1: "00:45",
    arrivalTime2: "08:45",
    cost: "909",
    departure: "Dubai",
    departureTime1: "15:45",
    departureTime2: "23:45",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Priority boarding, Braille safety cards, Special meals",
    arrival: "Hamburg",
    arrivalTime1: "03:00",
    arrivalTime2: "11:00",
    cost: "760",
    departure: "Sharjah",
    departureTime1: "19:00",
    departureTime2: "03:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Accessible lavatories, Wheelchair assistance, Special seating arrangements",
    arrival: "Cologne",
    arrivalTime1: "06:30",
    arrivalTime2: "14:30",
    cost: "1015",
    departure: "Dubai",
    departureTime1: "21:30",
    departureTime2: "05:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Wheelchair assistance, Sign language interpretation, In-flight medical assistance, Special meals, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime1: "15:00",
    arrivalTime2: "23:00",
    cost: "1088",
    departure: "Abu Dhabi",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Braille safety cards, Special meals, Wheelchair assistance, Priority boarding",
    arrival: "Munich",
    arrivalTime1: "15:15",
    arrivalTime2: "23:15",
    cost: "782",
    departure: "Sharjah",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special seating arrangements, Sign language interpretation",
    arrival: "Frankfurt",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "968",
    departure: "Dubai",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Special meals, Accessible lavatories, Special seating arrangements, Sign language interpretation, Priority boarding",
    arrival: "Berlin",
    arrivalTime1: "01:45",
    arrivalTime2: "09:45",
    cost: "1077",
    departure: "Abu Dhabi",
    departureTime1: "16:45",
    departureTime2: "00:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Special seating arrangements, In-flight medical assistance, Wheelchair assistance",
    arrival: "Hamburg",
    arrivalTime1: "04:00",
    arrivalTime2: "12:00",
    cost: "993",
    departure: "Dubai",
    departureTime1: "19:00",
    departureTime2: "03:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Special seating arrangements, Priority boarding, Special meals, Sign language interpretation, Accessible check-in counters",
    arrival: "Cologne",
    arrivalTime1: "04:30",
    arrivalTime2: "12:30",
    cost: "729",
    departure: "Sharjah",
    departureTime1: "22:30",
    departureTime2: "06:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Accessible check-in counters, Extra legroom, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime1: "17:00",
    arrivalTime2: "01:00",
    cost: "908",
    departure: "Dubai",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Special seating arrangements, Wheelchair assistance, Extra legroom",
    arrival: "Munich",
    arrivalTime1: "20:30",
    arrivalTime2: "04:30",
    cost: "1042",
    departure: "Abu Dhabi",
    departureTime1: "11:30",
    departureTime2: "19:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority baggage handling, Visual and auditory aids, Accessible lavatories",
    arrival: "Frankfurt",
    arrivalTime1: "20:45",
    arrivalTime2: "04:45",
    cost: "756",
    departure: "Sharjah",
    departureTime1: "14:45",
    departureTime2: "22:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Visual and auditory aids, Special meals",
    arrival: "Berlin",
    arrivalTime1: "03:00",
    arrivalTime2: "11:00",
    cost: "948",
    departure: "Dubai",
    departureTime1: "18:00",
    departureTime2: "02:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Priority baggage handling, Wheelchair assistance",
    arrival: "Hamburg",
    arrivalTime1: "06:30",
    arrivalTime2: "14:30",
    cost: "1027",
    departure: "Abu Dhabi",
    departureTime1: "21:30",
    departureTime2: "05:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "In-flight medical assistance, Braille safety cards, Visual and auditory aids, Extra legroom",
    arrival: "Cologne",
    arrivalTime1: "14:00",
    arrivalTime2: "22:00",
    cost: "930",
    departure: "Dubai",
    departureTime1: "05:00",
    departureTime2: "13:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Special meals, Accessible lavatories, Accessible check-in counters, Visual and auditory aids",
    arrival: "Dusseldorf",
    arrivalTime1: "15:15",
    arrivalTime2: "23:15",
    cost: "767",
    departure: "Sharjah",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible check-in counters, Sign language interpretation, Accessible lavatories",
    arrival: "Munich",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "995",
    departure: "Dubai",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority boarding, Accessible lavatories, Special seating arrangements, Extra legroom, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime1: "14:00",
    arrivalTime2: "22:00",
    cost: "782",
    departure: "Sharjah",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Special meals, Priority baggage handling, Sign language interpretation",
    arrival: "Hamburg",
    arrivalTime1: "19:30",
    arrivalTime2: "03:30",
    cost: "1017",
    departure: "Dubai",
    departureTime1: "10:30",
    departureTime2: "18:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities: "Accessible lavatories, Special seating arrangements",
    arrival: "Cologne",
    arrivalTime1: "23:45",
    arrivalTime2: "07:45",
    cost: "1070",
    departure: "Abu Dhabi",
    departureTime1: "14:45",
    departureTime2: "22:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Visual and auditory aids, Priority boarding",
    arrival: "Dusseldorf",
    arrivalTime1: "03:00",
    arrivalTime2: "11:00",
    cost: "986",
    departure: "Dubai",
    departureTime1: "18:00",
    departureTime2: "02:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "In-flight medical assistance, Special seating arrangements, Special meals, Extra legroom, Sign language interpretation",
    arrival: "Munich",
    arrivalTime1: "06:30",
    arrivalTime2: "14:30",
    cost: "1046",
    departure: "Abu Dhabi",
    departureTime1: "21:30",
    departureTime2: "05:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Accessible check-in counters, Braille safety cards, Extra legroom, Special meals",
    arrival: "Frankfurt",
    arrivalTime1: "11:00",
    arrivalTime2: "19:00",
    cost: "754",
    departure: "Sharjah",
    departureTime1: "05:00",
    departureTime2: "13:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Special seating arrangements, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime1: "18:15",
    arrivalTime2: "02:15",
    cost: "973",
    departure: "Dubai",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Sign language interpretation, Accessible check-in counters, Visual and auditory aids",
    arrival: "Hamburg",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "918",
    departure: "Abu Dhabi",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "In-flight medical assistance, Visual and auditory aids, Braille safety cards, Sign language interpretation",
    arrival: "Cologne",
    arrivalTime1: "22:45",
    arrivalTime2: "06:45",
    cost: "732",
    departure: "Sharjah",
    departureTime1: "16:45",
    departureTime2: "00:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Braille safety cards, Priority boarding, Visual and auditory aids, Special seating arrangements",
    arrival: "Dusseldorf",
    arrivalTime1: "05:00",
    arrivalTime2: "13:00",
    cost: "1027",
    departure: "Dubai",
    departureTime1: "20:00",
    departureTime2: "04:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "In-flight medical assistance, Priority boarding",
    arrival: "Munich",
    arrivalTime1: "12:00",
    arrivalTime2: "20:00",
    cost: "785",
    departure: "Sharjah",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Accessible check-in counters, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime1: "18:15",
    arrivalTime2: "02:15",
    cost: "988",
    departure: "Dubai",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities: "Priority baggage handling, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "1068",
    departure: "Abu Dhabi",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "In-flight medical assistance, Special seating arrangements, Visual and auditory aids, Sign language interpretation",
    arrival: "Hamburg",
    arrivalTime1: "01:45",
    arrivalTime2: "09:45",
    cost: "938",
    departure: "Dubai",
    departureTime1: "16:45",
    departureTime2: "00:45",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special seating arrangements, Special meals",
    arrival: "Cologne",
    arrivalTime1: "05:00",
    arrivalTime2: "13:00",
    cost: "1037",
    departure: "Abu Dhabi",
    departureTime1: "20:00",
    departureTime2: "04:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority baggage handling, Special meals, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime1: "12:00",
    arrivalTime2: "20:00",
    cost: "778",
    departure: "Sharjah",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Priority baggage handling, In-flight medical assistance",
    arrival: "Munich",
    arrivalTime1: "18:45",
    arrivalTime2: "02:45",
    cost: "978",
    departure: "Dubai",
    departureTime1: "09:45",
    departureTime2: "17:45",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Special seating arrangements, Wheelchair assistance, In-flight medical assistance, Priority boarding, Visual and auditory aids",
    arrival: "Frankfurt",
    arrivalTime1: "22:00",
    arrivalTime2: "06:00",
    cost: "1081",
    departure: "Abu Dhabi",
    departureTime1: "13:00",
    departureTime2: "21:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Accessible lavatories, Priority boarding, Special meals",
    arrival: "Berlin",
    arrivalTime1: "23:15",
    arrivalTime2: "07:15",
    cost: "800",
    departure: "Sharjah",
    departureTime1: "17:15",
    departureTime2: "01:15",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "In-flight medical assistance, Special seating arrangements, Priority boarding, Wheelchair assistance, Visual and auditory aids",
    arrival: "Hamburg",
    arrivalTime1: "05:30",
    arrivalTime2: "13:30",
    cost: "938",
    departure: "Dubai",
    departureTime1: "20:30",
    departureTime2: "04:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Visual and auditory aids, Accessible check-in counters, Wheelchair assistance, Accessible lavatories",
    arrival: "Berlin",
    arrivalTime1: "16:00",
    arrivalTime2: "00:00",
    cost: "888",
    departure: "Dubai",
    departureTime1: "08:00",
    departureTime2: "16:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities: "Sign language interpretation, Accessible check-in counters",
    arrival: "Hamburg",
    arrivalTime1: "19:30",
    arrivalTime2: "03:30",
    cost: "985",
    departure: "Abu Dhabi",
    departureTime1: "10:30",
    departureTime2: "18:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Special seating arrangements, In-flight medical assistance",
    arrival: "Cologne",
    arrivalTime1: "20:45",
    arrivalTime2: "04:45",
    cost: "761",
    departure: "Sharjah",
    departureTime1: "14:45",
    departureTime2: "22:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Braille safety cards, Accessible lavatories, Priority baggage handling",
    arrival: "Dusseldorf",
    arrivalTime1: "03:00",
    arrivalTime2: "11:00",
    cost: "1035",
    departure: "Dubai",
    departureTime1: "18:00",
    departureTime2: "02:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Visual and auditory aids, Accessible check-in counters, Special meals, Priority boarding, Wheelchair assistance",
    arrival: "Munich",
    arrivalTime1: "06:30",
    arrivalTime2: "14:30",
    cost: "1069",
    departure: "Abu Dhabi",
    departureTime1: "21:30",
    departureTime2: "05:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority boarding, Special seating arrangements, Special meals, Priority baggage handling, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime1: "11:00",
    arrivalTime2: "19:00",
    cost: "720",
    departure: "Sharjah",
    departureTime1: "05:00",
    departureTime2: "13:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Braille safety cards, Priority boarding, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime1: "18:15",
    arrivalTime2: "02:15",
    cost: "1053",
    departure: "Abu Dhabi",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Accessible check-in counters, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "1018",
    departure: "Dubai",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "In-flight medical assistance, Extra legroom, Priority boarding, Priority baggage handling",
    arrival: "Cologne",
    arrivalTime1: "01:45",
    arrivalTime2: "09:45",
    cost: "910",
    departure: "Abu Dhabi",
    departureTime1: "16:45",
    departureTime2: "00:45",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Extra legroom, Accessible lavatories, Visual and auditory aids, Sign language interpretation, Special meals",
    arrival: "Dusseldorf",
    arrivalTime1: "02:00",
    arrivalTime2: "10:00",
    cost: "811",
    departure: "Sharjah",
    departureTime1: "20:00",
    departureTime2: "04:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Special meals, Accessible lavatories, Braille safety cards, Extra legroom",
    arrival: "Munich",
    arrivalTime1: "15:00",
    arrivalTime2: "23:00",
    cost: "997",
    departure: "Dubai",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Braille safety cards, Special meals, Sign language interpretation, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime1: "18:15",
    arrivalTime2: "02:15",
    cost: "1066",
    departure: "Abu Dhabi",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Special meals, Extra legroom",
    arrival: "Berlin",
    arrivalTime1: "18:30",
    arrivalTime2: "02:30",
    cost: "745",
    departure: "Sharjah",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities: "Braille safety cards, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime1: "01:45",
    arrivalTime2: "09:45",
    cost: "946",
    departure: "Dubai",
    departureTime1: "16:45",
    departureTime2: "00:45",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Priority boarding, Accessible check-in counters, In-flight medical assistance",
    arrival: "Cologne",
    arrivalTime1: "05:00",
    arrivalTime2: "13:00",
    cost: "1037",
    departure: "Abu Dhabi",
    departureTime1: "20:00",
    departureTime2: "04:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Priority boarding, Visual and auditory aids",
    arrival: "Dusseldorf",
    arrivalTime1: "15:00",
    arrivalTime2: "23:00",
    cost: "1048",
    departure: "Dubai",
    departureTime1: "06:00",
    departureTime2: "14:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Accessible check-in counters, Wheelchair assistance, Priority boarding, Accessible lavatories",
    arrival: "Munich",
    arrivalTime1: "15:15",
    arrivalTime2: "23:15",
    cost: "800",
    departure: "Sharjah",
    departureTime1: "09:15",
    departureTime2: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "In-flight medical assistance, Priority boarding",
    arrival: "Frankfurt",
    arrivalTime1: "21:30",
    arrivalTime2: "05:30",
    cost: "981",
    departure: "Dubai",
    departureTime1: "12:30",
    departureTime2: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Accessible lavatories, Wheelchair assistance, Extra legroom, Sign language interpretation",
    arrival: "Berlin",
    arrivalTime1: "01:45",
    arrivalTime2: "09:45",
    cost: "1083",
    departure: "Abu Dhabi",
    departureTime1: "16:45",
    departureTime2: "00:45",
    duration: "6h 00m",
  },
];
