module.exports = [
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, In-flight medical assistance",
    arrival: "Paris",
    arrivalTime: "10:45",
    cost: "120",
    departure: "Berlin",
    departureTime: "08:00",
    duration: "2h 45m",
  },
  {
    airlines: "Air France",
    ammenities: "Braille safety cards, Priority boarding",
    arrival: "Nice",
    arrivalTime: "12:45",
    cost: "150",
    departure: "Frankfurt",
    departureTime: "10:30",
    duration: "2h 15m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Wheelchair assistance, In-flight medical assistance, Extra legroom, Sign language interpretation",
    arrival: "Marseille",
    arrivalTime: "15:45",
    cost: "95",
    departure: "Munich",
    departureTime: "13:15",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Visual and auditory aids, Extra legroom, Special seating arrangements, Special meals",
    arrival: "Lyon",
    arrivalTime: "18:30",
    cost: "75",
    departure: "Hamburg",
    departureTime: "16:00",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Special seating arrangements, Accessible check-in counters, In-flight medical assistance, Accessible lavatories, Braille safety cards",
    arrival: "Toulouse",
    arrivalTime: "22:15",
    cost: "60",
    departure: "Dusseldorf",
    departureTime: "19:30",
    duration: "2h 45m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Priority baggage handling, Wheelchair assistance, Special seating arrangements, Special meals, Sign language interpretation",
    arrival: "Bordeaux",
    arrivalTime: "10:15",
    cost: "90",
    departure: "Cologne",
    departureTime: "07:45",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "In-flight medical assistance, Priority boarding, Special seating arrangements",
    arrival: "Marseille",
    arrivalTime: "12:30",
    cost: "80",
    departure: "Berlin",
    departureTime: "10:00",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Sign language interpretation, Priority boarding, Priority baggage handling, Wheelchair assistance, Special seating arrangements",
    arrival: "Lyon",
    arrivalTime: "13:45",
    cost: "110",
    departure: "Munich",
    departureTime: "11:15",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Sign language interpretation, Wheelchair assistance, Extra legroom, Special seating arrangements, Special meals",
    arrival: "Nice",
    arrivalTime: "17:00",
    cost: "135",
    departure: "Hamburg",
    departureTime: "14:30",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Braille safety cards, Priority boarding, Visual and auditory aids, Special seating arrangements, In-flight medical assistance",
    arrival: "Paris",
    arrivalTime: "20:00",
    cost: "100",
    departure: "Frankfurt",
    departureTime: "18:00",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Priority boarding, Accessible lavatories, Wheelchair assistance, Special seating arrangements, Visual and auditory aids",
    arrival: "Toulouse",
    arrivalTime: "23:00",
    cost: "70",
    departure: "Cologne",
    departureTime: "20:30",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Priority boarding, Priority baggage handling, Wheelchair assistance, Special seating arrangements, In-flight medical assistance",
    arrival: "Marseille",
    arrivalTime: "09:15",
    cost: "95",
    departure: "Stuttgart",
    departureTime: "06:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible check-in counters, In-flight medical assistance, Visual and auditory aids, Sign language interpretation, Braille safety cards",
    arrival: "Nice",
    arrivalTime: "11:30",
    cost: "120",
    departure: "Dusseldorf",
    departureTime: "09:00",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Special seating arrangements, Visual and auditory aids, Accessible lavatories, Sign language interpretation, In-flight medical assistance",
    arrival: "Lyon",
    arrivalTime: "14:30",
    cost: "110",
    departure: "Berlin",
    departureTime: "12:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Priority boarding, Braille safety cards",
    arrival: "Bordeaux",
    arrivalTime: "17:45",
    cost: "85",
    departure: "Munich",
    departureTime: "15:15",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities: "Accessible check-in counters, Extra legroom",
    arrival: "Toulouse",
    arrivalTime: "20:15",
    cost: "65",
    departure: "Frankfurt",
    departureTime: "17:30",
    duration: "2h 45m",
  },
  {
    airlines: "EasyJet",
    ammenities: "Visual and auditory aids, Special meals",
    arrival: "Marseille",
    arrivalTime: "22:30",
    cost: "90",
    departure: "Hamburg",
    departureTime: "20:00",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Accessible check-in counters, Special meals, Extra legroom, In-flight medical assistance, Accessible lavatories",
    arrival: "Lyon",
    arrivalTime: "11:00",
    cost: "130",
    departure: "Dusseldorf",
    departureTime: "08:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "In-flight medical assistance, Accessible lavatories",
    arrival: "Nice",
    arrivalTime: "14:00",
    cost: "115",
    departure: "Berlin",
    departureTime: "11:30",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Extra legroom, Special seating arrangements",
    arrival: "Toulouse",
    arrivalTime: "17:15",
    cost: "80",
    departure: "Stuttgart",
    departureTime: "14:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Sign language interpretation, Accessible check-in counters, Accessible lavatories",
    arrival: "Marseille",
    arrivalTime: "09:00",
    cost: "130",
    departure: "Frankfurt",
    departureTime: "06:30",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Accessible check-in counters, Sign language interpretation, Priority baggage handling, Special meals, Extra legroom",
    arrival: "Toulouse",
    arrivalTime: "11:45",
    cost: "110",
    departure: "Berlin",
    departureTime: "09:15",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Accessible check-in counters, Priority baggage handling, Braille safety cards, Special meals",
    arrival: "Bordeaux",
    arrivalTime: "14:30",
    cost: "90",
    departure: "Hamburg",
    departureTime: "12:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Priority baggage handling, Extra legroom",
    arrival: "Nice",
    arrivalTime: "17:15",
    cost: "95",
    departure: "Munich",
    departureTime: "15:15",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Priority boarding, Special seating arrangements, Visual and auditory aids, Wheelchair assistance",
    arrival: "Paris",
    arrivalTime: "20:45",
    cost: "55",
    departure: "Cologne",
    departureTime: "18:45",
    duration: "2h",
  },
  {
    airlines: "Air France",
    ammenities: "Sign language interpretation, Accessible check-in counters",
    arrival: "Marseille",
    arrivalTime: "00:45",
    cost: "140",
    departure: "Dusseldorf",
    departureTime: "22:30",
    duration: "2h 15m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Priority baggage handling, Priority boarding, Special seating arrangements, Braille safety cards, In-flight medical assistance",
    arrival: "Nice",
    arrivalTime: "10:00",
    cost: "85",
    departure: "Berlin",
    departureTime: "07:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible check-in counters, Sign language interpretation, Priority baggage handling, In-flight medical assistance",
    arrival: "Lyon",
    arrivalTime: "12:45",
    cost: "120",
    departure: "Frankfurt",
    departureTime: "10:15",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Special meals, Accessible check-in counters, Braille safety cards",
    arrival: "Toulouse",
    arrivalTime: "16:15",
    cost: "85",
    departure: "Munich",
    departureTime: "13:45",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Extra legroom, In-flight medical assistance, Sign language interpretation, Special meals",
    arrival: "Marseille",
    arrivalTime: "18:45",
    cost: "70",
    departure: "Hamburg",
    departureTime: "16:30",
    duration: "2h 15m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Special meals, Priority boarding, In-flight medical assistance, Braille safety cards",
    arrival: "Bordeaux",
    arrivalTime: "21:30",
    cost: "105",
    departure: "Cologne",
    departureTime: "19:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Extra legroom, Visual and auditory aids",
    arrival: "Nice",
    arrivalTime: "11:00",
    cost: "100",
    departure: "Stuttgart",
    departureTime: "08:45",
    duration: "2h 15m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Braille safety cards, Accessible check-in counters, Special meals, Sign language interpretation",
    arrival: "Paris",
    arrivalTime: "13:30",
    cost: "70",
    departure: "Dusseldorf",
    departureTime: "11:30",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Visual and auditory aids, Priority baggage handling, Extra legroom",
    arrival: "Toulouse",
    arrivalTime: "16:30",
    cost: "75",
    departure: "Berlin",
    departureTime: "14:00",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, Special meals, Accessible check-in counters",
    arrival: "Bordeaux",
    arrivalTime: "20:15",
    cost: "110",
    departure: "Munich",
    departureTime: "17:45",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities: "Braille safety cards, Accessible lavatories, Extra legroom",
    arrival: "Marseille",
    arrivalTime: "22:30",
    cost: "125",
    departure: "Frankfurt",
    departureTime: "20:00",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Special meals, Braille safety cards",
    arrival: "Nice",
    arrivalTime: "09:15",
    cost: "80",
    departure: "Hamburg",
    departureTime: "07:15",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Accessible check-in counters, Priority baggage handling, Extra legroom, Special seating arrangements, Accessible lavatories",
    arrival: "Lyon",
    arrivalTime: "12:30",
    cost: "65",
    departure: "Cologne",
    departureTime: "10:00",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Accessible check-in counters, Priority baggage handling, Sign language interpretation, Wheelchair assistance",
    arrival: "Toulouse",
    arrivalTime: "15:45",
    cost: "90",
    departure: "Stuttgart",
    departureTime: "13:15",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Accessible lavatories, Sign language interpretation, Accessible check-in counters, Visual and auditory aids, Braille safety cards",
    arrival: "Bordeaux",
    arrivalTime: "19:00",
    cost: "130",
    departure: "Dusseldorf",
    departureTime: "16:30",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities: "Priority baggage handling, Extra legroom",
    arrival: "Nice",
    arrivalTime: "08:00",
    cost: "110",
    departure: "Munich",
    departureTime: "06:00",
    duration: "2h",
  },
  {
    airlines: "Eurowings",
    ammenities: "Braille safety cards, Priority boarding",
    arrival: "Bordeaux",
    arrivalTime: "12:00",
    cost: "90",
    departure: "Berlin",
    departureTime: "09:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Priority baggage handling, Braille safety cards, Special seating arrangements, Visual and auditory aids, Priority boarding",
    arrival: "Lyon",
    arrivalTime: "14:45",
    cost: "120",
    departure: "Frankfurt",
    departureTime: "12:15",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Priority baggage handling, Priority boarding, Visual and auditory aids, Special meals",
    arrival: "Toulouse",
    arrivalTime: "17:30",
    cost: "80",
    departure: "Hamburg",
    departureTime: "15:00",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Sign language interpretation, Visual and auditory aids, Accessible lavatories, Braille safety cards",
    arrival: "Marseille",
    arrivalTime: "20:15",
    cost: "70",
    departure: "Stuttgart",
    departureTime: "18:15",
    duration: "2h",
  },
  {
    airlines: "Air France",
    ammenities: "Accessible check-in counters, Extra legroom",
    arrival: "Nice",
    arrivalTime: "23:30",
    cost: "120",
    departure: "Cologne",
    departureTime: "21:30",
    duration: "2h",
  },
  {
    airlines: "Eurowings",
    ammenities: "Priority baggage handling, Visual and auditory aids",
    arrival: "Bordeaux",
    arrivalTime: "10:15",
    cost: "95",
    departure: "Dusseldorf",
    departureTime: "07:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Special meals, Accessible lavatories, Extra legroom",
    arrival: "Toulouse",
    arrivalTime: "13:00",
    cost: "130",
    departure: "Munich",
    departureTime: "10:30",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "In-flight medical assistance, Sign language interpretation, Special meals, Braille safety cards",
    arrival: "Marseille",
    arrivalTime: "15:45",
    cost: "75",
    departure: "Berlin",
    departureTime: "13:15",
    duration: "2h 30m",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Extra legroom, Priority baggage handling, Sign language interpretation, Special seating arrangements, Priority boarding",
    arrival: "Nice",
    arrivalTime: "18:00",
    cost: "80",
    departure: "Frankfurt",
    departureTime: "16:00",
    duration: "2h",
  },
  {
    airlines: "Air France",
    ammenities:
      "Visual and auditory aids, Special seating arrangements, Priority boarding, Braille safety cards",
    arrival: "Lyon",
    arrivalTime: "21:45",
    cost: "110",
    departure: "Hamburg",
    departureTime: "19:15",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Extra legroom, Visual and auditory aids, Priority baggage handling, Sign language interpretation, Braille safety cards",
    arrival: "Toulouse",
    arrivalTime: "00:30",
    cost: "90",
    departure: "Cologne",
    departureTime: "22:00",
    duration: "2h 30m",
  },
  {
    airlines: "Ryanair",
    ammenities: "Accessible check-in counters, Visual and auditory aids",
    arrival: "Bordeaux",
    arrivalTime: "10:00",
    cost: "70",
    departure: "Stuttgart",
    departureTime: "07:30",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible lavatories, Priority boarding, Sign language interpretation, Special seating arrangements",
    arrival: "Nice",
    arrivalTime: "12:15",
    cost: "105",
    departure: "Dusseldorf",
    departureTime: "10:15",
    duration: "2h",
  },
  {
    airlines: "EasyJet",
    ammenities:
      "Special seating arrangements, Braille safety cards, Visual and auditory aids, Special meals, Extra legroom",
    arrival: "Lyon",
    arrivalTime: "16:15",
    cost: "85",
    departure: "Munich",
    departureTime: "13:45",
    duration: "2h 30m",
  },
  {
    airlines: "Air France",
    ammenities:
      "Priority boarding, Visual and auditory aids, Sign language interpretation, Accessible check-in counters",
    arrival: "Marseille",
    arrivalTime: "19:00",
    cost: "120",
    departure: "Berlin",
    departureTime: "16:30",
    duration: "2h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Extra legroom, Priority boarding, Priority baggage handling",
    arrival: "Toulouse",
    arrivalTime: "22:15",
    cost: "95",
    departure: "Frankfurt",
    departureTime: "19:45",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible lavatories, Priority boarding, Visual and auditory aids",
    arrival: "Nice",
    arrivalTime: "08:00",
    cost: "110",
    departure: "Hamburg",
    departureTime: "06:00",
    duration: "2h",
  },
  {
    airlines: "Ryanair",
    ammenities:
      "Accessible check-in counters, Wheelchair assistance, Sign language interpretation",
    arrival: "Marseille",
    arrivalTime: "11:45",
    cost: "80",
    departure: "Cologne",
    departureTime: "09:30",
    duration: "2h 15m",
  },
  {
    airlines: "EasyJet",
    ammenities: "Visual and auditory aids, Sign language interpretation",
    arrival: "Lyon",
    arrivalTime: "14:30",
    cost: "90",
    departure: "Dusseldorf",
    departureTime: "12:00",
    duration: "2h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Accessible check-in counters, Special meals, Braille safety cards, Sign language interpretation",
    arrival: "Paris",
    arrivalTime: "10:45",
    cost: "120",
    departure: "Berlin",
    departureTime: "08:00",
    duration: "2h 45m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Sign language interpretation, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime: "11:30",
    cost: "500",
    departure: "Toronto",
    departureTime: "08:00",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Accessible lavatories, Accessible check-in counters",
    arrival: "Frankfurt",
    arrivalTime: "16:30",
    cost: "550",
    departure: "Montreal",
    departureTime: "12:15",
    duration: "9h 15m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Special seating arrangements, Braille safety cards, Priority baggage handling",
    arrival: "Hamburg",
    arrivalTime: "19:30",
    cost: "450",
    departure: "Vancouver",
    departureTime: "15:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Sign language interpretation, Braille safety cards, Priority baggage handling, Extra legroom, Visual and auditory aids",
    arrival: "Cologne",
    arrivalTime: "03:00",
    cost: "400",
    departure: "Calgary",
    departureTime: "21:30",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Wheelchair assistance, Accessible lavatories, Extra legroom",
    arrival: "Dusseldorf",
    arrivalTime: "11:00",
    cost: "520",
    departure: "Toronto",
    departureTime: "07:45",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Priority baggage handling, Extra legroom, Accessible check-in counters",
    arrival: "Munich",
    arrivalTime: "15:00",
    cost: "570",
    departure: "Montreal",
    departureTime: "10:30",
    duration: "8h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Accessible lavatories, Priority boarding",
    arrival: "Berlin",
    arrivalTime: "17:45",
    cost: "480",
    departure: "Vancouver",
    departureTime: "13:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Accessible check-in counters, Priority baggage handling",
    arrival: "Frankfurt",
    arrivalTime: "22:30",
    cost: "430",
    departure: "Calgary",
    departureTime: "16:00",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Priority boarding, In-flight medical assistance",
    arrival: "Hamburg",
    arrivalTime: "22:30",
    cost: "510",
    departure: "Toronto",
    departureTime: "19:15",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Visual and auditory aids, Braille safety cards, Accessible lavatories",
    arrival: "Cologne",
    arrivalTime: "02:30",
    cost: "550",
    departure: "Montreal",
    departureTime: "22:00",
    duration: "9h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Visual and auditory aids, Accessible check-in counters, Braille safety cards",
    arrival: "Dusseldorf",
    arrivalTime: "12:00",
    cost: "470",
    departure: "Vancouver",
    departureTime: "07:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Priority baggage handling, Special meals",
    arrival: "Munich",
    arrivalTime: "16:45",
    cost: "420",
    departure: "Calgary",
    departureTime: "10:15",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Braille safety cards, Priority boarding, Special meals, Priority baggage handling, Accessible lavatories",
    arrival: "Berlin",
    arrivalTime: "17:00",
    cost: "530",
    departure: "Toronto",
    departureTime: "13:45",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Extra legroom, Priority baggage handling, Braille safety cards, Wheelchair assistance, Sign language interpretation",
    arrival: "Frankfurt",
    arrivalTime: "21:00",
    cost: "590",
    departure: "Vancouver",
    departureTime: "16:30",
    duration: "9h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Sign language interpretation, Priority boarding, In-flight medical assistance",
    arrival: "Hamburg",
    arrivalTime: "12:30",
    cost: "460",
    departure: "Calgary",
    departureTime: "06:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Braille safety cards, Extra legroom",
    arrival: "Cologne",
    arrivalTime: "13:45",
    cost: "520",
    departure: "Toronto",
    departureTime: "09:30",
    duration: "9h 15m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Special seating arrangements, Visual and auditory aids, Priority boarding",
    arrival: "Dusseldorf",
    arrivalTime: "16:30",
    cost: "490",
    departure: "Montreal",
    departureTime: "12:00",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Priority boarding, In-flight medical assistance, Priority baggage handling, Accessible check-in counters",
    arrival: "Munich",
    arrivalTime: "22:00",
    cost: "550",
    departure: "Vancouver",
    departureTime: "16:30",
    duration: "10h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "Accessible check-in counters, Extra legroom, Braille safety cards, Priority baggage handling",
    arrival: "Berlin",
    arrivalTime: "02:15",
    cost: "440",
    departure: "Calgary",
    departureTime: "19:45",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Special meals, Special seating arrangements, Extra legroom, Wheelchair assistance, Priority baggage handling",
    arrival: "Frankfurt",
    arrivalTime: "02:15",
    cost: "",
    departure: "Toronto",
    departureTime: "22:00",
    duration: "8h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "In-flight medical assistance, Accessible lavatories",
    arrival: "rankfurt",
    arrivalTime: "13:30",
    cost: "600",
    departure: "Ottawa",
    departureTime: "08:30",
    duration: "9h 00m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Braille safety cards, Special meals, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime: "18:15",
    cost: "550",
    departure: "Edmonton",
    departureTime: "11:45",
    duration: "10h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities:
      "In-flight medical assistance, Extra legroom, Special meals, Priority boarding",
    arrival: "Dusseldorf",
    arrivalTime: "19:30",
    cost: "500",
    departure: "Halifax",
    departureTime: "15:00",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Priority boarding, In-flight medical assistance",
    arrival: "Munich",
    arrivalTime: "00:15",
    cost: "450",
    departure: "Vancouver",
    departureTime: "18:45",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, Accessible check-in counters",
    arrival: "Hamburg",
    arrivalTime: "12:45",
    cost: "580",
    departure: "Montreal",
    departureTime: "08:15",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Wheelchair assistance, Priority baggage handling, Visual and auditory aids",
    arrival: "Cologne",
    arrivalTime: "15:45",
    cost: "540",
    departure: "Toronto",
    departureTime: "11:30",
    duration: "9h 15m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Accessible lavatories, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime: "18:30",
    cost: "520",
    departure: "Halifax",
    departureTime: "14:00",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special meals, Wheelchair assistance, Accessible lavatories, Priority boarding, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime: "22:00",
    cost: "520",
    departure: "Calgary",
    departureTime: "16:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities: "Accessible lavatories, Wheelchair assistance",
    arrival: "Dusseldorf",
    arrivalTime: "01:45",
    cost: "470",
    departure: "Edmonton",
    departureTime: "19:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Visual and auditory aids, In-flight medical assistance, Special seating arrangements",
    arrival: "Munich",
    arrivalTime: "10:45",
    cost: "590",
    departure: "Toronto",
    departureTime: "06:30",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Extra legroom, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime: "14:30",
    cost: "560",
    departure: "Vancouver",
    departureTime: "10:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Wheelchair assistance, Special meals, Sign language interpretation",
    arrival: "Cologne",
    arrivalTime: "18:15",
    cost: "530",
    departure: "Montreal",
    departureTime: "13:45",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Accessible lavatories, Special meals, Priority boarding",
    arrival: "Berlin",
    arrivalTime: "21:00",
    cost: "550",
    departure: "Ottawa",
    departureTime: "16:30",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special meals, Visual and auditory aids",
    arrival: "Frankfurt",
    arrivalTime: "02:15",
    cost: "480",
    departure: "Edmonton",
    departureTime: "19:45",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Special meals, Sign language interpretation, Extra legroom",
    arrival: "Dusseldorf",
    arrivalTime: "12:30",
    cost: "510",
    departure: "Vancouver",
    departureTime: "08:00",
    duration: "10h 30m",
  },
  {
    airlines: "Eurowings",
    ammenities: "Accessible lavatories, Visual and auditory aids",
    arrival: "Munich",
    arrivalTime: "15:45",
    cost: "540",
    departure: "Halifax",
    departureTime: "11:15",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "In-flight medical assistance, Priority boarding, Special meals",
    arrival: "Hamburg",
    arrivalTime: "22:15",
    cost: "480",
    departure: "Calgary",
    departureTime: "15:45",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Priority boarding, Sign language interpretation",
    arrival: "Cologne",
    arrivalTime: "22:30",
    cost: "550",
    departure: "Vancouver",
    departureTime: "18:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Priority baggage handling, Extra legroom, Visual and auditory aids, Sign language interpretation, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime: "11:45",
    cost: "590",
    departure: "Toronto",
    departureTime: "07:30",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Accessible lavatories, Sign language interpretation, Priority boarding",
    arrival: "Frankfurt",
    arrivalTime: "14:45",
    cost: "610",
    departure: "Montreal",
    departureTime: "10:15",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Braille safety cards, Visual and auditory aids, Extra legroom",
    arrival: "Hamburg",
    arrivalTime: "16:00",
    cost: "550",
    departure: "Edmonton",
    departureTime: "09:30",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Extra legroom, Priority boarding",
    arrival: "Cologne",
    arrivalTime: "17:30",
    cost: "530",
    departure: "Calgary",
    departureTime: "12:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Wheelchair assistance, Special seating arrangements, Priority baggage handling, Visual and auditory aids",
    arrival: "Berlin",
    arrivalTime: "21:45",
    cost: "470",
    departure: "Vancouver",
    departureTime: "15:15",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special seating arrangements, Accessible check-in counters",
    arrival: "Frankfurt",
    arrivalTime: "22:45",
    cost: "560",
    departure: "Toronto",
    departureTime: "18:30",
    duration: "9h 15m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Special seating arrangements, Braille safety cards, Extra legroom, Accessible lavatories, Special meals",
    arrival: "Dusseldorf",
    arrivalTime: "01:30",
    cost: "580",
    departure: "Halifax",
    departureTime: "21:00",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "In-flight medical assistance, Priority baggage handling, Special meals, Braille safety cards, Extra legroom",
    arrival: "Munich",
    arrivalTime: "14:15",
    cost: "520",
    departure: "Edmonton",
    departureTime: "07:45",
    duration: "10h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special meals, Extra legroom, Visual and auditory aids, Accessible lavatories, Accessible check-in counters",
    arrival: "Hamburg",
    arrivalTime: "16:45",
    cost: "540",
    departure: "Calgary",
    departureTime: "11:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Accessible check-in counters, Priority boarding",
    arrival: "Cologne",
    arrivalTime: "19:00",
    cost: "500",
    departure: "Vancouver",
    departureTime: "14:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Visual and auditory aids, Accessible lavatories, Sign language interpretation",
    arrival: "Berlin",
    arrivalTime: "21:15",
    cost: "550",
    departure: "Toronto",
    departureTime: "17:00",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Sign language interpretation, Priority boarding, Braille safety cards, Special seating arrangements",
    arrival: "Frankfurt",
    arrivalTime: "01:15",
    cost: "590",
    departure: "Halifax",
    departureTime: "20:45",
    duration: "9h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Extra legroom, Accessible lavatories, In-flight medical assistance",
    arrival: "Dusseldorf",
    arrivalTime: "14:00",
    cost: "530",
    departure: "Vancouver",
    departureTime: "09:30",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities: "Priority boarding, Extra legroom",
    arrival: "Munich",
    arrivalTime: "18:30",
    cost: "570",
    departure: "Calgary",
    departureTime: "13:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Priority boarding, Priority baggage handling, In-flight medical assistance, Braille safety cards",
    arrival: "Hamburg",
    arrivalTime: "20:30",
    cost: "580",
    departure: "Toronto",
    departureTime: "16:15",
    duration: "9h 15m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Priority baggage handling, Priority boarding, Extra legroom",
    arrival: "Cologne",
    arrivalTime: "00:00",
    cost: "510",
    departure: "Halifax",
    departureTime: "19:30",
    duration: "9h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Wheelchair assistance, Visual and auditory aids, In-flight medical assistance",
    arrival: "Berlin",
    arrivalTime: "04:30",
    cost: "540",
    departure: "Edmonton",
    departureTime: "22:00",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Priority baggage handling, Special meals, Braille safety cards, Wheelchair assistance, Special seating arrangements",
    arrival: "Frankfurt",
    arrivalTime: "13:15",
    cost: "490",
    departure: "Calgary",
    departureTime: "06:45",
    duration: "10h 30m",
  },
  {
    airlines: "Air Canada",
    ammenities:
      "Sign language interpretation, Special seating arrangements, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime: "14:45",
    cost: "570",
    departure: "Toronto",
    departureTime: "10:30",
    duration: "9h 15m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Special seating arrangements, Accessible check-in counters, Sign language interpretation, Wheelchair assistance",
    arrival: "Munich",
    arrivalTime: "18:30",
    cost: "500",
    departure: "Halifax",
    departureTime: "14:00",
    duration: "9h 30m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Special seating arrangements, Visual and auditory aids, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime: "21:45",
    cost: "560",
    departure: "Vancouver",
    departureTime: "17:15",
    duration: "10h 30m",
  },
  {
    airlines: "Air Transat",
    ammenities:
      "Braille safety cards, Accessible check-in counters, Wheelchair assistance",
    arrival: "Cologne",
    arrivalTime: "00:45",
    cost: "530",
    departure: "Toronto",
    departureTime: "20:30",
    duration: "9h 15m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Visual and auditory aids, Special meals, Sign language interpretation, Priority baggage handling, Accessible check-in counters",
    arrival: "Munich",
    arrivalTime: "19:00",
    cost: "480",
    departure: "Dubai",
    departureTime: "10:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Accessible lavatories, Wheelchair assistance, Braille safety cards, Sign language interpretation",
    arrival: "Frankfurt",
    arrivalTime: "22:30",
    cost: "520",
    departure: "Abu Dhabi",
    departureTime: "13:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Special seating arrangements, Accessible lavatories, Priority boarding",
    arrival: "Berlin",
    arrivalTime: "00:45",
    cost: "460",
    departure: "Dubai",
    departureTime: "15:45",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Priority boarding, Braille safety cards, Special meals",
    arrival: "Hamburg",
    arrivalTime: "03:00",
    cost: "380",
    departure: "Sharjah",
    departureTime: "19:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Accessible lavatories, Wheelchair assistance, Special seating arrangements",
    arrival: "Cologne",
    arrivalTime: "06:30",
    cost: "510",
    departure: "Dubai",
    departureTime: "21:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Wheelchair assistance, Sign language interpretation, In-flight medical assistance, Special meals, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime: "15:00",
    cost: "550",
    departure: "Abu Dhabi",
    departureTime: "06:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Braille safety cards, Special meals, Wheelchair assistance, Priority boarding",
    arrival: "Munich",
    arrivalTime: "15:15",
    cost: "400",
    departure: "Sharjah",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special seating arrangements, Sign language interpretation",
    arrival: "Frankfurt",
    arrivalTime: "21:30",
    cost: "490",
    departure: "Dubai",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Special meals, Accessible lavatories, Special seating arrangements, Sign language interpretation, Priority boarding",
    arrival: "Berlin",
    arrivalTime: "01:45",
    cost: "540",
    departure: "Abu Dhabi",
    departureTime: "16:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Special seating arrangements, In-flight medical assistance, Wheelchair assistance",
    arrival: "Hamburg",
    arrivalTime: "04:00",
    cost: "500",
    departure: "Dubai",
    departureTime: "19:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Special seating arrangements, Priority boarding, Special meals, Sign language interpretation, Accessible check-in counters",
    arrival: "Cologne",
    arrivalTime: "04:30",
    cost: "370",
    departure: "Sharjah",
    departureTime: "22:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Accessible check-in counters, Extra legroom, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime: "17:00",
    cost: "460",
    departure: "Dubai",
    departureTime: "08:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Special seating arrangements, Wheelchair assistance, Extra legroom",
    arrival: "Munich",
    arrivalTime: "20:30",
    cost: "530",
    departure: "Abu Dhabi",
    departureTime: "11:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority baggage handling, Visual and auditory aids, Accessible lavatories",
    arrival: "Frankfurt",
    arrivalTime: "20:45",
    cost: "380",
    departure: "Sharjah",
    departureTime: "14:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Visual and auditory aids, Special meals",
    arrival: "Berlin",
    arrivalTime: "03:00",
    cost: "480",
    departure: "Dubai",
    departureTime: "18:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Priority baggage handling, Wheelchair assistance",
    arrival: "Hamburg",
    arrivalTime: "06:30",
    cost: "520",
    departure: "Abu Dhabi",
    departureTime: "21:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "In-flight medical assistance, Braille safety cards, Visual and auditory aids, Extra legroom",
    arrival: "Cologne",
    arrivalTime: "14:00",
    cost: "470",
    departure: "Dubai",
    departureTime: "05:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Special meals, Accessible lavatories, Accessible check-in counters, Visual and auditory aids",
    arrival: "Dusseldorf",
    arrivalTime: "15:15",
    cost: "390",
    departure: "Sharjah",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Accessible check-in counters, Sign language interpretation, Accessible lavatories",
    arrival: "Munich",
    arrivalTime: "21:30",
    cost: "500",
    departure: "Dubai",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority boarding, Accessible lavatories, Special seating arrangements, Extra legroom, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime: "14:00",
    cost: "400",
    departure: "Sharjah",
    departureTime: "08:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Special meals, Priority baggage handling, Sign language interpretation",
    arrival: "Hamburg",
    arrivalTime: "19:30",
    cost: "510",
    departure: "Dubai",
    departureTime: "10:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities: "Accessible lavatories, Special seating arrangements",
    arrival: "Cologne",
    arrivalTime: "23:45",
    cost: "540",
    departure: "Abu Dhabi",
    departureTime: "14:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Visual and auditory aids, Priority boarding",
    arrival: "Dusseldorf",
    arrivalTime: "03:00",
    cost: "500",
    departure: "Dubai",
    departureTime: "18:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "In-flight medical assistance, Special seating arrangements, Special meals, Extra legroom, Sign language interpretation",
    arrival: "Munich",
    arrivalTime: "06:30",
    cost: "530",
    departure: "Abu Dhabi",
    departureTime: "21:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Accessible check-in counters, Braille safety cards, Extra legroom, Special meals",
    arrival: "Frankfurt",
    arrivalTime: "11:00",
    cost: "380",
    departure: "Sharjah",
    departureTime: "05:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Visual and auditory aids, Special seating arrangements, Accessible check-in counters",
    arrival: "Berlin",
    arrivalTime: "18:15",
    cost: "490",
    departure: "Dubai",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Sign language interpretation, Accessible check-in counters, Visual and auditory aids",
    arrival: "Hamburg",
    arrivalTime: "21:30",
    cost: "460",
    departure: "Abu Dhabi",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "In-flight medical assistance, Visual and auditory aids, Braille safety cards, Sign language interpretation",
    arrival: "Cologne",
    arrivalTime: "22:45",
    cost: "370",
    departure: "Sharjah",
    departureTime: "16:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Braille safety cards, Priority boarding, Visual and auditory aids, Special seating arrangements",
    arrival: "Dusseldorf",
    arrivalTime: "05:00",
    cost: "520",
    departure: "Dubai",
    departureTime: "20:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "In-flight medical assistance, Priority boarding",
    arrival: "Munich",
    arrivalTime: "12:00",
    cost: "400",
    departure: "Sharjah",
    departureTime: "06:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Accessible check-in counters, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime: "18:15",
    cost: "500",
    departure: "Dubai",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities: "Priority baggage handling, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime: "21:30",
    cost: "540",
    departure: "Abu Dhabi",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "In-flight medical assistance, Special seating arrangements, Visual and auditory aids, Sign language interpretation",
    arrival: "Hamburg",
    arrivalTime: "01:45",
    cost: "470",
    departure: "Dubai",
    departureTime: "16:45",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities: "Special seating arrangements, Special meals",
    arrival: "Cologne",
    arrivalTime: "05:00",
    cost: "520",
    departure: "Abu Dhabi",
    departureTime: "20:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority baggage handling, Special meals, Accessible lavatories",
    arrival: "Dusseldorf",
    arrivalTime: "12:00",
    cost: "390",
    departure: "Sharjah",
    departureTime: "06:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Priority baggage handling, In-flight medical assistance",
    arrival: "Munich",
    arrivalTime: "18:45",
    cost: "490",
    departure: "Dubai",
    departureTime: "09:45",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Special seating arrangements, Wheelchair assistance, In-flight medical assistance, Priority boarding, Visual and auditory aids",
    arrival: "Frankfurt",
    arrivalTime: "22:00",
    cost: "550",
    departure: "Abu Dhabi",
    departureTime: "13:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Accessible lavatories, Priority boarding, Special meals",
    arrival: "Berlin",
    arrivalTime: "23:15",
    cost: "400",
    departure: "Sharjah",
    departureTime: "17:15",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "In-flight medical assistance, Special seating arrangements, Priority boarding, Wheelchair assistance, Visual and auditory aids",
    arrival: "Hamburg",
    arrivalTime: "05:30",
    cost: "470",
    departure: "Dubai",
    departureTime: "20:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "Visual and auditory aids, Accessible check-in counters, Wheelchair assistance, Accessible lavatories",
    arrival: "Berlin",
    arrivalTime: "16:00",
    cost: "450",
    departure: "Dubai",
    departureTime: "08:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities: "Sign language interpretation, Accessible check-in counters",
    arrival: "Hamburg",
    arrivalTime: "19:30",
    cost: "500",
    departure: "Abu Dhabi",
    departureTime: "10:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Special seating arrangements, In-flight medical assistance",
    arrival: "Cologne",
    arrivalTime: "20:45",
    cost: "390",
    departure: "Sharjah",
    departureTime: "14:45",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Braille safety cards, Accessible lavatories, Priority baggage handling",
    arrival: "Dusseldorf",
    arrivalTime: "03:00",
    cost: "520",
    departure: "Dubai",
    departureTime: "18:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Visual and auditory aids, Accessible check-in counters, Special meals, Priority boarding, Wheelchair assistance",
    arrival: "Munich",
    arrivalTime: "06:30",
    cost: "540",
    departure: "Abu Dhabi",
    departureTime: "21:30",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Priority boarding, Special seating arrangements, Special meals, Priority baggage handling, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime: "11:00",
    cost: "370",
    departure: "Sharjah",
    departureTime: "05:00",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Braille safety cards, Priority boarding, Wheelchair assistance",
    arrival: "Berlin",
    arrivalTime: "18:15",
    cost: "530",
    departure: "Abu Dhabi",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Accessible check-in counters, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime: "21:30",
    cost: "510",
    departure: "Dubai",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities:
      "In-flight medical assistance, Extra legroom, Priority boarding, Priority baggage handling",
    arrival: "Cologne",
    arrivalTime: "01:45",
    cost: "460",
    departure: "Abu Dhabi",
    departureTime: "16:45",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Extra legroom, Accessible lavatories, Visual and auditory aids, Sign language interpretation, Special meals",
    arrival: "Dusseldorf",
    arrivalTime: "02:00",
    cost: "410",
    departure: "Sharjah",
    departureTime: "20:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities:
      "Special meals, Accessible lavatories, Braille safety cards, Extra legroom",
    arrival: "Munich",
    arrivalTime: "15:00",
    cost: "500",
    departure: "Dubai",
    departureTime: "06:00",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Braille safety cards, Special meals, Sign language interpretation, In-flight medical assistance",
    arrival: "Frankfurt",
    arrivalTime: "18:15",
    cost: "540",
    departure: "Abu Dhabi",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities: "Special meals, Extra legroom",
    arrival: "Berlin",
    arrivalTime: "18:30",
    cost: "380",
    departure: "Sharjah",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Flydubai",
    ammenities: "Braille safety cards, Accessible lavatories",
    arrival: "Hamburg",
    arrivalTime: "01:45",
    cost: "480",
    departure: "Dubai",
    departureTime: "16:45",
    duration: "6h 00m",
  },
  {
    airlines: "Lufthansa",
    ammenities:
      "Priority boarding, Accessible check-in counters, In-flight medical assistance",
    arrival: "Cologne",
    arrivalTime: "05:00",
    cost: "520",
    departure: "Abu Dhabi",
    departureTime: "20:00",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "Priority boarding, Visual and auditory aids",
    arrival: "Dusseldorf",
    arrivalTime: "15:00",
    cost: "530",
    departure: "Dubai",
    departureTime: "06:00",
    duration: "6h 00m",
  },
  {
    airlines: "Air Arabia",
    ammenities:
      "Accessible check-in counters, Wheelchair assistance, Priority boarding, Accessible lavatories",
    arrival: "Munich",
    arrivalTime: "15:15",
    cost: "400",
    departure: "Sharjah",
    departureTime: "09:15",
    duration: "6h 00m",
  },
  {
    airlines: "Emirates",
    ammenities: "In-flight medical assistance, Priority boarding",
    arrival: "Frankfurt",
    arrivalTime: "21:30",
    cost: "500",
    departure: "Dubai",
    departureTime: "12:30",
    duration: "6h 00m",
  },
  {
    airlines: "Etihad Airways",
    ammenities:
      "Accessible lavatories, Wheelchair assistance, Extra legroom, Sign language interpretation",
    arrival: "Berlin",
    arrivalTime: "01:45",
    cost: "550",
    departure: "Abu Dhabi",
    departureTime: "16:45",
    duration: "6h 00m",
  },
];
